"""
Seed pipeline script to generate high-density, structured content for:
1. Interview Questions (150+ questions across 9 categories)
2. Vocabulary Packs (350+ terms across 7 engineering packs with IPA, definitions, examples)
3. Grammar Units (32 units across 4 CEFR levels with Hispanic pitfalls and STAR interview applications)
Incorporates taxonomy and resources from awesome-english (yvoronoy/awesome-english).
"""

import json
import os

def build_interview_questions():
    questions = []
    
    # 1. HR & Behavioral (20 questions)
    hr_data = [
        ("Tell me about yourself", "Can you walk me through your background, your main technical interests, and what brings you to this role?",
         "I have been focusing on full-stack software development with Python and Flutter, building scalable backend services and responsive client interfaces. I thrive when solving complex architectural problems and delivering clean, well-tested code.",
         "Use the Present, Past, Future structure: what you do now, past relevant projects, and why this role matches your career trajectory.", "junior"),
        ("Greatest Strength", "What would you say is your greatest technical or professional strength?",
         "My greatest strength is my systematic problem-solving mindset. When faced with an unfamiliar bug or legacy codebase, I isolate root causes with reproducible benchmarks rather than guessing.",
         "Back your claim with a concrete, concise technical story.", "junior"),
        ("Area for Improvement", "What is an area where you feel you need improvement, and what steps are you taking to address it?",
         "In the past, I tended to optimize edge cases before gathering feedback. Now, I share early architectural design docs and prototypes with the team to align sooner.",
         "Pick a real professional skill, show active remediation, and avoid cliché non-answers.", "junior"),
        ("Handling Disagreement", "Describe a situation where you had a technical disagreement with a colleague. How did you resolve it?",
         "We debated whether to use PostgreSQL or a document store for our event log. Rather than arguing subjectively, I drafted a quick benchmark comparing our read/write patterns, and we decided collaboratively based on data.",
         "Focus on emotional intelligence, objective evidence, and constructive compromise.", "mid"),
        ("Why This Company", "Why are you interested in joining our engineering team specifically?",
         "I admire your team's commitment to clean architecture, high reliability, and self-hosted infrastructure. Building robust solutions that directly impact users is exactly the environment I thrive in.",
         "Demonstrate knowledge of their product and engineering philosophy.", "junior"),
        ("Tight Deadlines", "Tell me about a time when a deadline was approaching and you realized you wouldn't be able to finish all scope.",
         "I immediately audited the task backlog to separate core MVP deliverables from nice-to-have features, communicated transparently with the product lead, and delivered the critical user journey on schedule.",
         "Highlight proactive communication and ruthless prioritization.", "mid"),
        ("A Mistake You Made", "Can you share an experience where you made a mistake on a project and how you resolved it?",
         "Early on, I missed a migration script before deploying a minor update, causing launch crashes. I quickly rolled back, corrected the schema migration, and added an automated CI check to prevent regressions.",
         "Own the mistake, emphasize rapid resolution, and demonstrate the lesson learned.", "junior"),
        ("Learning Quickly", "Tell me about a time you had to master a new tool or framework under tight time constraints.",
         "I needed to integrate Docker and local speech-to-text models within three days. I read official docs, inspected open-source samples, built a minimal proof of concept, and successfully containerized the pipeline.",
         "Emphasize your learning methodology and hands-on resourcefulness.", "mid"),
        ("Mentoring Others", "How do you approach sharing knowledge or onboarding new members into a codebase?",
         "I believe in clear documentation and pair programming. I maintain up-to-date architectural diagrams and walk newcomers through real pull requests to build confidence.",
         "Show patience, leadership, and structured communication.", "senior"),
        ("Three Year Vision", "Where do you envision your career progressing over the next two to three years?",
         "I want to become a well-rounded senior engineer capable of designing distributed backend architectures and driving end-to-end features with high autonomy.",
         "Align your ambition with engineering depth and business impact.", "mid"),
        ("Handling Feedback", "How do you handle critical code review feedback on your pull requests?",
         "I view code reviews as a collaborative learning mechanism. If a reviewer points out a cleaner pattern or edge case, I thank them and apply the fix. If I disagree, I explain the trade-offs respectfully with benchmarks.",
         "Show humility and technical rigor.", "junior"),
        ("Managing Ambiguity", "Describe how you proceed when product requirements are vague or incomplete.",
         "I schedule a brief alignment call with the product manager, list the key user assumptions and boundary conditions, document them in a RFC or user story, and obtain sign-off before writing code.",
         "Highlight proactive stakeholder communication.", "mid"),
        ("Working with Non-Tech Stakeholders", "How do you explain technical debt or complex infrastructure to business executives?",
         "I use business analogies: technical debt is like financial interest that slows down our feature delivery speed. I quantify the impact in terms of maintenance costs and uptime risk.",
         "Avoid engineering jargon; speak in terms of revenue, risk, and velocity.", "senior"),
        ("Overcoming Burnout / Pressure", "How do you maintain code quality and personal focus during intense production sprints?",
         "I rely on disciplined time-blocking, automated test coverage, and frequent communication with my lead so that scope adjustments happen before quality is compromised.",
         "Show emotional resilience and mature planning habits.", "mid"),
        ("Leading an Initiative", "Have you ever initiated an improvement that was not explicitly assigned to you?",
         "Yes, our test suite took 25 minutes in CI. I analyzed the bottlenecks, parallelized the test runners, and reduced execution time to 6 minutes, saving hours across the team every week.",
         "Focus on initiative, quantifiable team impact, and proactive ownership.", "senior"),
        ("Cross-functional Conflict", "How do you handle tension between engineering best practices and sales wanting rapid hacks?",
         "I separate immediate customer validation from long-term stability. We implement a lightweight feature flag for validation, with an agreed sprint allocated for refactoring if adopted.",
         "Demonstrate balanced business acumen.", "senior"),
        ("Handling Legacy Code", "What is your mindset when taking over an undocumented legacy codebase?",
         "I start by writing characterization unit tests around critical user paths. Once I understand the existing behavior, I refactor incrementally without introducing regressions.",
         "Emphasize safety, testing, and incremental improvement.", "mid"),
        ("Remote Work Discipline", "How do you stay aligned and productive in an asynchronous, remote-first team?",
         "I over-communicate in written form: clear PR descriptions, detailed tickets, Loom screen recordings when helpful, and daily status summaries to eliminate blockers.",
         "Highlight written clarity and autonomous execution.", "junior"),
        ("Failing a Production SLA", "How did you react during a major customer-facing outage you were responsible for?",
         "I stayed calm, focused immediately on mitigation and rollback, kept the incident commander updated, and later led a blameless post-mortem to patch the root cause.",
         "Emphasize composure, blameless culture, and systemic fixes.", "senior"),
        ("Salary & Role Expectations", "What are your expectations regarding ownership and technical scope in your next role?",
         "I am looking for an environment where I have end-to-end ownership of services, where code reviews are rigorous, and where technical excellence is recognized and cultivated.",
         "Be clear, positive, and aligned with company stage.", "mid"),
    ]
    
    for title, text, model, tips, diff in hr_data:
        questions.append({
            "id": len(questions) + 1,
            "category": "hr",
            "difficulty": diff,
            "title": title,
            "text": text,
            "model_answer": model,
            "tips": tips
        })

    # 2. Core Technical & Algorithms (35 questions)
    tech_data = [
        ("OOP Core Principles", "Can you explain the four core pillars of Object-Oriented Programming and give a brief example of polymorphism?",
         "The four pillars are Encapsulation, Abstraction, Inheritance, and Polymorphism. Polymorphism allows different classes to implement the same interface or method signature with custom behavior, like a Shape interface with different draw() implementations.",
         "Keep definitions crisp and provide a real-world coding analogy.", "junior"),
        ("Git: Rebase vs Merge", "What is the key difference between git merge and git rebase, and when would you choose one over the other?",
         "Git merge creates a new commit that joins two histories together, preserving the chronological sequence. Git rebase rewrites project history by moving feature branch commits onto the tip of main, producing a clean, linear git log. I use rebase for local feature branches before making a PR, and merge for main integration.",
         "Mention history rewriting and the Golden Rule of Rebase.", "junior"),
        ("REST API Constraints & HTTP Methods", "What makes an API RESTful, and how do you differentiate between PUT and PATCH methods?",
         "A REST API relies on stateless HTTP verbs, resource-oriented URIs, and standard status codes. PUT is idempotent and typically replaces the entire resource representation, while PATCH applies partial updates to specific fields.",
         "Explicitly mention idempotence and resource representation.", "junior"),
        ("Relational vs NoSQL Databases", "When would you choose a Relational Database like PostgreSQL over a Document Store like MongoDB?",
         "I choose relational databases when data integrity, ACID compliance, and structured relations across multiple entities are paramount. I prefer NoSQL document stores when dealing with polymorphic, rapidly shifting schemas or high-throughput write streams where horizontal sharding is essential.",
         "Discuss ACID, schema predictability, and query complexity.", "mid"),
        ("Indexing in SQL Databases", "How do database indexes work internally, and what is the trade-off of adding too many indexes?",
         "Indexes generally use B-Tree data structures to locate rows in logarithmic time O(log n) rather than scanning entire tables O(n). The trade-off is that every INSERT, UPDATE, and DELETE becomes slower because all relevant index trees must be updated, and they consume extra storage space.",
         "Explain B-Trees and the read vs write performance trade-off.", "mid"),
        ("Unit vs Integration vs E2E Testing", "Explain the testing pyramid: what is the difference between unit tests, integration tests, and end-to-end tests?",
         "Unit tests isolate individual functions or classes using mocks. Integration tests verify that multiple modules work together, such as an API route communicating with a test database. E2E tests validate the complete user journey through the UI and live services.",
         "Talk about execution speed, cost of maintenance, and confidence level.", "junior"),
        ("Asynchronous Programming and the Event Loop", "How does asynchronous I/O work in languages like Python (asyncio) or Dart, and why does it improve concurrency without multi-threading?",
         "It relies on a single-threaded event loop that schedules tasks. When an I/O operation like a network call or database query is waiting, the event loop yields control to execute other pending tasks, maximizing CPU utilization without the overhead and race conditions of multi-threading.",
         "Contrast I/O bound vs CPU bound workloads.", "mid"),
        ("Docker Containers vs Virtual Machines", "What is the architectural difference between a Docker container and a traditional Virtual Machine?",
         "Virtual Machines package an entire guest operating system and virtualize hardware via a hypervisor. Docker containers share the host Linux kernel and isolate processes using namespaces and cgroups, making them much lighter, faster to boot, and resource-efficient.",
         "Highlight the shared kernel vs hypervisor difference.", "mid"),
        ("Microservices vs Modular Monolith", "What are the benefits and pitfalls of moving from a monolith to microservices?",
         "Microservices offer independent deployments, technological flexibility, and isolation for individual teams. However, they introduce immense operational complexity: network latency, distributed transactions, observability hurdles, and deployment orchestration. A well-designed modular monolith is often the better starting choice.",
         "Demonstrate pragmatic engineering maturity over hype.", "senior"),
        ("Designing a Rate Limiter", "How would you design a distributed rate limiter for an API protecting against brute-force or abuse?",
         "I would implement a Token Bucket or Sliding Window Log algorithm using Redis. Each request increments or checks a key keyed by IP or user ID with an expiration TTL. Redis atomic operations ensure consistency across distributed API worker nodes.",
         "Mention Token Bucket algorithm and Redis atomic operations.", "senior"),
        ("State Management in Frontend / Flutter", "Why do we need specialized state management libraries like Riverpod or Bloc instead of just using setState?",
         "setState is scoped strictly to a single widget, which leads to prop drilling and hard-to-test monolithic widgets when state must be shared across disparate screens. Libraries like Riverpod decouple business logic from the UI layer, support dependency injection, and optimize rebuilds.",
         "Talk about separation of concerns, testability, and rebuild optimization.", "mid"),
        ("CI/CD Pipelines", "What is Continuous Integration and Continuous Deployment, and what stages belong in a healthy pipeline?",
         "Continuous Integration automatically builds and tests code changes on every commit to detect bugs early. Continuous Deployment automates deploying passing builds to staging or production. A healthy pipeline includes linting, unit tests, security scans, artifact creation, and smoke tests.",
         "Mention lint, test, build, and deploy stages.", "junior"),
        ("Caching Strategies", "Explain the difference between Cache-Aside and Write-Through caching patterns.",
         "In Cache-Aside, the application first queries the cache. On a miss, it fetches data from the database and updates the cache for future requests. In Write-Through, the application writes directly to the cache, which synchronously updates the underlying database.",
         "Discuss cache invalidation and data staleness.", "mid"),
        ("JWT vs Session Cookies", "How does stateless JWT authentication compare to server-side session cookies in terms of security and scalability?",
         "JWTs are self-contained and stateless, allowing any backend service to verify the signature without querying a central session database, which scales easily. However, revoking a leaked JWT immediately is challenging unless a blocklist is maintained. Session cookies are easily revocable on the server but require state lookup.",
         "Touch upon revocation, token expiration, and CSRF vs XSS.", "senior"),
        ("Handling Race Conditions", "What is a race condition and how can you mitigate it in a concurrent backend system?",
         "A race condition occurs when multiple threads or processes access and modify shared data concurrently, producing unpredictable outcomes. It can be mitigated using mutexes, optimistic locking with version columns, or pessimistic database row locks like SELECT FOR UPDATE.",
         "Explain optimistic vs pessimistic locking.", "mid"),
        ("SQL Joins: Inner vs Left vs Outer", "Briefly explain the differences between INNER JOIN, LEFT JOIN, and FULL OUTER JOIN in SQL.",
         "INNER JOIN returns only rows where there is a match in both tables. LEFT JOIN returns all rows from the left table and matched rows from the right table, with nulls where there is no match. FULL OUTER JOIN returns all rows from both tables, filling in nulls on either side.",
         "Use a mental Venn diagram and mention how NULL handling works.", "junior"),
        ("Understanding HTTP Status Codes", "Can you give common examples of 2xx, 3xx, 4xx, and 5xx HTTP response status codes and their semantic meanings?",
         "200 OK or 201 Created signify success. 301 or 302 indicate redirection. 400 Bad Request, 401 Unauthorized, and 404 Not Found represent client-side errors. 500 Internal Server Error and 503 Service Unavailable represent server-side failures.",
         "Emphasize the difference between 401 (unauthenticated) and 403 (forbidden).", "junior"),
        ("Cross-Origin Resource Sharing (CORS)", "What is CORS, why do browsers enforce it, and how does preflight OPTIONS work?",
         "CORS is a browser security mechanism that restricts web applications from making requests to a different domain than the one that served it. For non-simple requests, the browser sends an HTTP OPTIONS preflight request to verify server permissions via Access-Control-Allow headers.",
         "Clarify that CORS is enforced by browsers, not backends.", "mid"),
        ("Environment Variables and 12-Factor App", "Why should configuration be strictly separated from code using environment variables?",
         "Storing configuration such as database credentials and API keys in environment variables prevents secrets from leaking into version control and allows the same codebase to run seamlessly across development, staging, and production environments.",
         "Refer to the Twelve-Factor App methodology.", "mid"),
        ("WebSockets vs HTTP Polling", "When would you implement WebSockets instead of regular HTTP polling or Server-Sent Events (SSE)?",
         "I use WebSockets when full-duplex, bidirectional, low-latency communication is required, like in multiplayer games or chat apps. For unidirectional server-to-client updates like notification feeds, Server-Sent Events (SSE) is simpler and runs over standard HTTP.",
         "Compare full-duplex vs half-duplex and connection overhead.", "mid"),
        ("CAP Theorem", "Can you explain the CAP theorem and what choices a distributed system must make during network partitions?",
         "The CAP theorem states that a distributed system can guarantee at most two out of Consistency, Availability, and Partition Tolerance. Because network partitions are inevitable in real networks, distributed systems must trade off between consistency (CP) and availability (AP).",
         "Emphasize that Partition Tolerance is mandatory in distributed networks.", "senior"),
        ("What is a Deadlock?", "What causes a deadlock in concurrent software, and what conditions are required for it to occur?",
         "A deadlock occurs when two or more processes are unable to proceed because each is waiting for a resource locked by the other. It requires mutual exclusion, hold and wait, no preemption, and circular wait conditions.",
         "Mention the circular dependency condition and lock ordering solutions.", "junior"),
        ("Garbage Collection Mechanisms", "How does automatic memory management work in runtimes like JVM, V8, or Dart?",
         "Modern runtimes use generational garbage collection. Short-lived objects are allocated in a young generation and quickly collected by scavengers, while long-lived objects are promoted to an old generation and cleaned during mark-and-sweep cycles.",
         "Explain generational hypothesis and mark-sweep.", "senior"),
        ("Big O Notation & Complexity", "Why is Big O notation essential when selecting data structures for algorithmic tasks?",
         "Big O describes the upper bound of time or memory growth relative to input size n. It allows engineers to predict whether an algorithm will scale smoothly or degrade into quadratic or exponential slowdowns under production load.",
         "Contrast O(1), O(log n), O(n), and O(n^2) with concrete examples.", "junior"),
        ("Database Connection Pooling", "Why do we use connection pools like HikariCP or SQLAlchemy pooling instead of opening new connections per query?",
         "Establishing a TCP handshake, TLS negotiation, and database authentication takes 50-100ms. A connection pool keeps pre-warmed sockets open, reducing latency to under a millisecond and preventing database process exhaustion.",
         "Highlight socket reuse and connection storm prevention.", "mid"),
        ("TCP vs UDP Protocols", "What are the fundamental differences between TCP and UDP, and when is UDP preferred?",
         "TCP provides connection-oriented, reliable, ordered data delivery with error checking and congestion control. UDP is connectionless, lightweight, and unordered, making it ideal for real-time video streaming, DNS lookups, and gaming where low latency trumps reliability.",
         "Contrast reliability/overhead with raw throughput and packet loss tolerance.", "junior"),
        ("Hash Table Collisions", "How do hash maps handle collisions when two different keys hash to the same bucket?",
         "Hash maps handle collisions primarily through separate chaining (linked lists or balanced trees at each bucket) or open addressing (linear or quadratic probing into adjacent buckets).",
         "Mention worst-case degradation to O(n) and re-hashing.", "mid"),
        ("Immutable Infrastructure", "What does immutable infrastructure mean in modern cloud deployments?",
         "Instead of modifying or patching running servers in-place, servers or containers are never updated. Any code change results in building a new image and replacing the previous instances completely.",
         "Discuss drift prevention and reproducible blue-green deployments.", "senior"),
        ("Event-Driven Architecture", "What are the benefits of using an asynchronous message broker like RabbitMQ or Kafka between services?",
         "Message brokers decouple producers from consumers, provide temporal buffer during traffic spikes, and allow multiple services to react to business events independently without direct synchronous coupling.",
         "Contrast message queuing (point-to-point) with event streaming (log-based).", "senior"),
        ("SQL Injection Prevention", "What causes SQL injection and what is the single most effective defense against it?",
         "SQL injection occurs when untrusted user input is directly concatenated into SQL query strings. The single most effective defense is using parameterized queries or prepared statements, which separate the SQL code from user data.",
         "Emphasize parameterized queries over string sanitization regexes.", "junior"),
        ("DNS Resolution Process", "What happens step-by-step when your browser resolves a domain name like google.com?",
         "The browser checks local cache, asks the OS resolver, queries the recursive resolver (ISP/1.1.1.1), which in turn traverses Root servers, TLD servers (.com), and authoritative name servers to retrieve the A or AAAA IP record.",
         "Explain recursive vs authoritative DNS lookups.", "mid"),
        ("S.O.L.I.D. Principles", "Can you explain the Single Responsibility Principle and Open/Closed Principle with practical software examples?",
         "Single Responsibility states that a class should have one reason to change, meaning it handles a single concept. Open/Closed states that software entities should be open for extension but closed for modification, typically achieved via abstractions and interfaces.",
         "Focus on practical refactoring benefits rather than textbook recitation.", "mid"),
        ("Idempotency in Distributed Systems", "What does idempotency mean in payment processing or distributed API calls, and how is it implemented?",
         "An idempotent operation can be executed multiple times without changing the outcome beyond the initial call. It is implemented using unique idempotency keys sent by clients and tracked in a deduplication cache like Redis.",
         "Explain duplicate transaction prevention during network timeouts.", "senior"),
        ("Clean Architecture Layers", "How do you organize code layers in Clean Architecture or Hexagonal Architecture?",
         "Clean Architecture places core business entities and use cases at the center, isolated from external frameworks. Adapters, repositories, controllers, and UI sit in outer rings, depending inwards via interfaces.",
         "Mention the Dependency Inversion Principle across layer boundaries.", "senior"),
        ("Circuit Breaker Pattern", "What problem does a Circuit Breaker solve in distributed microservices?",
         "A Circuit Breaker prevents cascading failures when a downstream dependency is down or slow. It fails fast when error thresholds are exceeded, giving the degraded service time to recover and returning fallbacks immediately.",
         "Mention closed, open, and half-open states.", "senior"),
    ]
    for title, text, model, tips, diff in tech_data:
        questions.append({
            "id": len(questions) + 1,
            "category": "technical",
            "difficulty": diff,
            "title": title,
            "text": text,
            "model_answer": model,
            "tips": tips
        })

    # 3. Debugging & Live Incident Handling (20 questions)
    debug_data = [
        ("Diagnosing High Latency", "How do you systematically troubleshoot an API route that suddenly jumped from 50ms to 2.5s response time?",
         "I inspect distributed traces and APM metrics to locate the exact bottleneck: database query, external API call, or CPU contention. If it is database-related, I run EXPLAIN ANALYZE on the slow queries to detect missing indexes or sequential table scans.",
         "Structure your response: Observability -> Isolation -> Benchmark -> Resolution.", "mid"),
        ("Memory Leak in Long-Running Process", "How do you identify and fix a memory leak in a production backend service?",
         "I take progressive heap dumps over time and compare retained object allocations. Once I identify which objects fail to get garbage-collected—such as uncleared event listeners, global dictionaries, or open file descriptors—I patch the reference lifecycle.",
         "Mention heap profiling tools, retained size, and garbage collection roots.", "senior"),
        ("Handling a 502 Bad Gateway", "A customer reports intermittent 502 Bad Gateway errors on your web app. Where do you begin investigating?",
         "A 502 means the reverse proxy (like Nginx) received an invalid response or timeout from upstream app workers. I check Nginx error logs, verify upstream worker health, examine CPU/memory spikes, and check socket backlog limits.",
         "Clarify the role of reverse proxies vs application servers.", "junior"),
        ("Troubleshooting a Silent Failure", "How do you debug a background job that completes with status OK but doesn't perform the expected database updates?",
         "I inspect application transaction boundaries to verify whether changes were rolled back or never committed. I review debug logs with correlation IDs, verify exception handling blocks that might be swallowing errors, and replicate with a test fixture.",
         "Look for swallowed exceptions and uncommitted database transactions.", "mid"),
        ("Debugging Deadlocks in Production", "Two concurrent requests triggered a deadlock error in PostgreSQL. How do you analyze and resolve it?",
         "I query pg_stat_activity and the PostgreSQL deadlock log to identify the two competing transactions and the specific row locks involved. I resolve it by enforcing consistent alphabetical lock ordering across all transactions.",
         "Explain consistent lock ordering across concurrent code paths.", "senior"),
        ("Fixing Intermittent Flaky Tests", "How do you tackle a CI test suite that fails randomly on 5% of runs?",
         "I look for shared mutable state, non-deterministic timeouts, unseeded random generators, or race conditions in asynchronous callbacks. I isolate the failing test, run it in a stress loop (e.g. 100 iterations), and replace real timers with virtual clocks.",
         "Mention deterministic test environments and async awaiting.", "mid"),
        ("Investigating Disk Space Exhaustion", "A production server disk filled up to 100% and halted the database. How do you recover and ensure it doesn't repeat?",
         "First, I identify large non-critical files like uncompressed log archives or core dumps to free immediate headroom. Once the service recovers, I configure logrotate with strict size caps, set up disk usage alerts at 80%, and move backups to object storage.",
         "Separate immediate triage from long-term preventive automation.", "junior"),
        ("Troubleshooting High CPU Utilization", "An API service is spiking to 100% CPU on all cores. How do you identify which code path is responsible?",
         "I attach a sampling CPU profiler (like py-spy or perf) to generate a flame graph of the running process. This visually isolates whether CPU time is spent in regex backtracking, JSON parsing, crypto hashing, or tight calculation loops.",
         "Mention CPU profiling flame graphs and sampling profilers.", "senior"),
        ("Diagnosing Connection Pool Exhaustion", "Your application logs display 'Timeout waiting for connection from pool'. What are the probable root causes?",
         "Probable causes include leaked connections not being closed in finally blocks, long-running queries holding connections open while doing slow I/O, or a pool size configured too small for the concurrency level.",
         "Highlight connection leaks and holding connections during external I/O.", "mid"),
        ("Investigating Cache Invalidation Bugs", "Users report seeing stale profile data after updating their profile. How do you identify and fix the issue?",
         "I check whether the cache update relies on TTL expiration rather than event-driven invalidation. I verify whether write operations purge the specific cache key across all replicas and test for race conditions between write and read replicas.",
         "Discuss cache invalidation strategies and replication lag.", "mid"),
        ("Handling Broken Third-Party Webhooks", "A payment provider's webhooks stopped being processed 4 hours ago. What is your incident response?",
         "I check inbound gateway logs to verify whether webhooks arrived and failed signature verification or crashed upstream. Once the parsing bug is fixed, I trigger replay from the provider's dashboard or replay from our raw ingress event queue.",
         "Focus on idempotency and replayability of webhook payloads.", "senior"),
        ("Debugging Mobile App Crash on Launch", "Your Flutter/mobile app crashes immediately after launch for 10% of users on a new update. How do you triage?",
         "I check Crashlytics or Sentry for symbolicated stack traces. If the crash occurs before the first frame, it usually points to corrupted local SQLite migrations, missing native permissions, or null pointer exceptions in local secure storage.",
         "Mention crash reporting, local database migrations, and hotfix rollbacks.", "mid"),
        ("Troubleshooting Broken Websocket Connections", "Mobile clients frequently disconnect from your real-time WebSocket server. How do you diagnose?",
         "I verify keep-alive heartbeat ping/pong intervals, proxy idle timeout settings (like AWS ALB or Cloudflare 60s limit), and inspect client network state transitions (switching from Wi-Fi to cellular).",
         "Mention heartbeat intervals and reverse proxy idle timeouts.", "mid"),
        ("Analyzing Corrupted Data in Production", "A bug in a batch job inserted invalid timestamps across 50,000 records. How do you remediate safely?",
         "I stop the faulty job, back up the affected table, write a targeted SQL remediation script that runs inside an explicit transaction, verify the changes on a staging clone first, and execute in chunks to avoid locking the production table.",
         "Emphasize explicit transactions, pre-backup, and chunked updates.", "senior"),
        ("Diagnosing CORS Failures in Single Page Apps", "A frontend client receives 'No Access-Control-Allow-Origin header is present'. How do you resolve it cleanly?",
         "I check server CORS middleware configuration to ensure the requesting origin, HTTP methods, and custom headers are explicitly allowed. I ensure the backend handles the preflight OPTIONS request before running authentication middleware.",
         "Clarify preflight OPTIONS handling and credentials allowance.", "junior"),
        ("Debugging Slow Startup Times", "A containerized microservice takes 3 minutes to pass its initial healthcheck. How do you optimize it?",
         "I profile the bootstrap phase: heavy synchronous database seeding, blocking network calls to remote config services, or loading huge machine learning models on the main thread. I defer non-essential initializations or run them in parallel.",
         "Differentiate bootstrap blocking tasks from lazy loading.", "senior"),
        ("Troubleshooting SSL/TLS Certificate Errors", "An automated cron job fails with 'SSL: CERTIFICATE_VERIFY_FAILED'. What do you verify?",
         "I check if the server certificate has expired, if the CA bundle in the container runtime is outdated, or if a corporate firewall is intercepting TLS traffic with a custom self-signed certificate.",
         "Mention certificate expiration, root CA bundles, and trust stores.", "junior"),
        ("Analyzing Redis Memory Eviction", "Redis memory reached maxmemory and began dropping cached user sessions. How do you fix and prevent this?",
         "I inspect Redis INFO memory and memory keyspace. If volatile sessions were mixed with static cache, I separate them into different Redis instances, apply an appropriate eviction policy (like volatile-lru), and add Redis cluster alerting.",
         "Highlight separating critical state (sessions) from disposable cache.", "senior"),
        ("Debugging Race Conditions in File Uploads", "When users upload two files rapidly, only one file is saved correctly. What could be wrong?",
         "The backend might be using a static temporary filename instead of generating a unique UUID per upload stream, or there is an unhandled race condition in an asynchronous state variable overwriting the file pointer.",
         "Look for non-unique temp paths and shared state pointers.", "junior"),
        ("Writing an Incident Post-Mortem", "What are the core components of an effective blameless incident post-mortem?",
         "An effective post-mortem includes: executive summary, timeline of events, root cause analysis (5 Whys), impact assessment (users affected, downtime), what went well, what went poorly, and prioritized action items with assignees.",
         "Emphasize blameless culture and preventive systemic action items.", "senior"),
    ]
    for title, text, model, tips, diff in debug_data:
        questions.append({
            "id": len(questions) + 1,
            "category": "debugging",
            "difficulty": diff,
            "title": title,
            "text": text,
            "model_answer": model,
            "tips": tips
        })

    # 4. Databases & Data Pipelines (15 questions)
    db_data = [
        ("Database Normalization vs Denormalization", "What are 1NF, 2NF, and 3NF, and when is deliberate denormalization justified?",
         "1NF eliminates duplicate columns and requires atomic values. 2NF ensures non-key attributes depend on the entire primary key. 3NF removes transitive dependencies. Denormalization is justified in high-read analytical or reporting queries where JOIN overhead creates unacceptable latency.",
         "Explain normal forms and read-heavy optimization trade-offs.", "mid"),
        ("Database Sharding Strategies", "How does database sharding differ from read replicas, and what key strategies are used?",
         "Read replicas replicate the entire dataset to scale read capacity. Sharding partitions data horizontally across independent database nodes to scale both write throughput and storage. Strategies include Range-based, Hash-based, and Directory-based sharding.",
         "Contrast horizontal scaling of writes vs reads.", "senior"),
        ("Optimistic vs Pessimistic Concurrency Control", "When should you use optimistic locking with version columns versus SELECT FOR UPDATE?",
         "Optimistic locking is ideal for low-contention scenarios because it avoids holding locks and detects conflicts at commit time. Pessimistic locking (SELECT FOR UPDATE) is necessary in high-contention financial transactions where conflicts are frequent and failed retries are unacceptable.",
         "Contrast contention levels and retry overhead.", "mid"),
        ("PostgreSQL MVCC (Multi-Version Concurrency Control)", "How does MVCC allow PostgreSQL to read data without locking writers?",
         "MVCC keeps multiple physical versions of rows tagged with transaction IDs (xmin, xmax). Readers see a consistent snapshot of rows committed before their transaction began, allowing concurrent reads and writes without blocking each other.",
         "Mention row versions, transaction snapshots, and VACUUM cleanup.", "senior"),
        ("Write-Ahead Logging (WAL)", "What is the Write-Ahead Log in relational databases and why is it crucial for durability?",
         "WAL logs every state modification to append-only disk storage before updating database data pages. If a crash or power failure occurs, the database replays the WAL on reboot to guarantee ACID durability without losing committed transactions.",
         "Highlight crash recovery and sequential disk write performance.", "senior"),
        ("Designing Database Indexes for Multi-Column Queries", "How does column order matter in a composite database index (A, B, C)?",
         "A composite index follows the Leftmost Prefix rule. It can accelerate queries filtering on (A), (A, B), or (A, B, C), but cannot optimize queries filtering only on (B) or (C) alone. High-cardinality equality columns should typically come first.",
         "Explain the leftmost prefix rule and cardinality considerations.", "mid"),
        ("Zero-Downtime Database Migrations", "How do you add a non-nullable column to a table with 100 million rows without downtime?",
         "I use a multi-step migration: 1) Add the column as nullable. 2) Deploy app code that writes to both new and old fields. 3) Backfill historical rows in small batches. 4) Add the NOT NULL constraint with VALIDATE CONSTRAINT in PostgreSQL. 5) Deploy app reading strictly from new column.",
         "Break down the expand-and-contract migration pattern.", "senior"),
        ("Replication Lag & Read-Your-Own-Writes Consistency", "How do you guarantee that a user sees their newly published post when querying read replicas with replication lag?",
         "I route write requests to the primary database, and for a short window after a user write (e.g. 5 seconds), route that specific user's read requests to the primary database rather than the read replica.",
         "Explain read-your-own-writes consistency via sticky routing.", "senior"),
        ("Time-Series Databases vs Relational", "When would you choose TimescaleDB or InfluxDB over standard PostgreSQL for IoT or metrics?",
         "Time-series databases specialize in sequential timestamped data. They offer automated chunk partitioning by time, high-throughput ingest rates, automatic data retention policies, and columnar downsampling.",
         "Discuss timestamp indexing, continuous aggregates, and retention policies.", "mid"),
        ("Handling Soft Deletes vs Hard Deletes", "What are the trade-offs of using soft deletes (is_deleted boolean) in enterprise applications?",
         "Soft deletes preserve historical audit trails and enable easy undeletes. However, they complicate unique constraints, inflate table sizes, degrade index performance, and require adding 'WHERE is_deleted = false' to every query unless filtered views are used.",
         "Mention unique constraint complications and partial indexing.", "mid"),
        ("Database Transaction Isolation Levels", "Can you explain Read Uncommitted, Read Committed, Repeatable Read, and Serializable?",
         "They represent progressive isolation against concurrency anomalies. Read Committed prevents dirty reads. Repeatable Read prevents non-repeatable reads. Serializable prevents phantom reads and serialization anomalies, but has the highest lock contention.",
         "Explain dirty reads, non-repeatable reads, and phantom reads.", "senior"),
        ("Vector Databases in Modern AI Architectures", "What is the purpose of vector databases like pgvector, Qdrant, or Pinecone in LLM applications?",
         "Vector databases store high-dimensional embeddings generated by neural models. They use Approximate Nearest Neighbor (ANN) indexing algorithms like HNSW to execute semantic similarity searches in milliseconds.",
         "Mention embeddings, high-dimensionality, and HNSW indexing.", "mid"),
        ("Managing N+1 Query Problems in ORMs", "What is the N+1 query problem in ORMs like SQLAlchemy or Prisma, and how do you prevent it?",
         "The N+1 problem occurs when fetching N records triggers N additional individual queries to load related foreign entities. It is resolved using eager loading (joinedload or selectinload in SQLAlchemy) to fetch related entities in a single batch query.",
         "Explain lazy loading pitfalls and eager loading solutions.", "junior"),
        ("Database Connection Leaks in Microservices", "How do you detect and fix leaked connections in an async Python or Go service?",
         "I monitor open database connection pool metrics over time. If active connections continuously rise without returning to the pool, I inspect exception handlers to ensure all sessions are wrapped in context managers (with / try-finally blocks).",
         "Mention context managers and connection pool telemetry.", "mid"),
        ("ETL vs ELT in Data Pipelines", "What is the difference between traditional ETL and modern ELT in cloud data warehouses like BigQuery or Snowflake?",
         "In ETL, data is transformed by an intermediate server before loading into the warehouse. In ELT, raw data is loaded directly into the cloud data warehouse first, leveraging the warehouse's massive distributed compute engine to execute transformations via SQL (e.g. dbt).",
         "Contrast data warehouse scalability with intermediate compute servers.", "mid"),
    ]
    for title, text, model, tips, diff in db_data:
        questions.append({
            "id": len(questions) + 1,
            "category": "databases",
            "difficulty": diff,
            "title": title,
            "text": text,
            "model_answer": model,
            "tips": tips
        })

    # 5. APIs & Microservices (15 questions)
    api_data = [
        ("gRPC vs REST APIs", "When would you adopt gRPC with Protocol Buffers instead of standard JSON REST APIs?",
         "I adopt gRPC for internal service-to-service communication requiring high throughput, low latency, and strict schema contracts. Protobuf encodes binary payloads with minimal serialization overhead, and HTTP/2 enables multiplexing and bidirectional streaming.",
         "Compare binary serialization vs JSON and HTTP/2 multiplexing.", "mid"),
        ("API Versioning Strategies", "What are the common approaches to API versioning (URI, header, query) and their trade-offs?",
         "URI path versioning (/v1/users) is transparent, easy to cache, and straightforward for consumers. Header versioning (Accept: application/vnd.app.v1+json) keeps URIs clean and REST-compliant but is harder to test in browsers.",
         "Discuss URI path vs header versioning with caching implications.", "junior"),
        ("GraphQL vs REST", "What specific architectural pain points does GraphQL resolve compared to REST?",
         "GraphQL eliminates over-fetching and under-fetching by allowing client queries to specify exact fields needed, and aggregates multiple resource lookups into a single network round-trip. However, it complicates caching and rate-limiting.",
         "Discuss over-fetching, under-fetching, and caching complexity.", "mid"),
        ("Handling Distributed Transactions: Sagas", "How does the Saga pattern manage data consistency across microservices without two-phase commit (2PC)?",
         "A Saga executes a sequence of local transactions across individual services. Each transaction updates its own database and publishes an event. If a step fails, the Saga coordinates compensating transactions to undo the previous changes gracefully.",
         "Explain choreography vs orchestration and compensating transactions.", "senior"),
        ("API Gateway Responsibilities", "What responsibilities belong in an API Gateway like Kong, Envoy, or KrakenD?",
         "An API Gateway centralizes cross-cutting concerns: SSL termination, client authentication, rate limiting, request routing, telemetry aggregation, and payload transformation, freeing backend microservices from duplicate boilerplate.",
         "Highlight cross-cutting concerns and decoupling.", "mid"),
        ("BFF Pattern (Backend for Frontend)", "Why would you introduce a Backend for Frontend (BFF) layer in a multi-client application?",
         "Different clients (mobile, web, smartwatch) have distinct screen sizes, network constraints, and data requirements. A BFF provides dedicated, optimized API endpoints tailored to each client type without bloating core backend microservices.",
         "Explain client-specific data shaping and network optimization.", "mid"),
        ("OAuth2 Grant Types & PKCE", "Why is Authorization Code Flow with PKCE recommended for Single Page Apps and mobile clients?",
         "Public clients cannot securely store client secrets without decompilation risk. PKCE (Proof Key for Code Exchange) uses dynamic cryptographically hashed verifiers to ensure the party redeeming the authorization code is the identical party that requested it.",
         "Explain public client limitations and cryptographic code verifiers.", "senior"),
        ("Designing Idempotent POST Endpoints", "How do you make an order checkout POST endpoint resilient against network retries?",
         "The client generates a unique UUID idempotency key for the purchase attempt. The server uses an atomic check-and-set in Redis: if the key exists, it returns the cached response; if not, it processes the payment and stores the result.",
         "Mention unique client idempotency keys and atomic deduplication.", "senior"),
        ("Contract Testing with Pact", "What is Consumer-Driven Contract Testing and how does it prevent broken API integrations?",
         "Consumer-Driven Contract Testing allows client teams to define expectations (contracts) of API responses. The API provider verifies these contracts against its build pipeline, ensuring breaking schema changes are caught before deployment.",
         "Contrast contract testing with end-to-end integration environments.", "mid"),
        ("Webhooks vs Polling for Asynchronous Events", "How do you design a reliable outbound webhook delivery system for third parties?",
         "I publish webhook events to a durable message queue. Dedicated workers send HTTP POST requests with signature verification headers (HMAC). If the recipient returns non-2xx, the worker applies exponential backoff retries and dead-letter queues.",
         "Mention durable queuing, exponential backoff, and HMAC signatures.", "senior"),
        ("SSE (Server-Sent Events) vs WebSockets", "Why is Server-Sent Events often preferred over WebSockets for AI streaming completions?",
         "LLM token generation is strictly unidirectional (server to client). SSE runs over standard HTTP/1.1 or HTTP/2, supports automatic browser reconnection out-of-the-box, works seamlessly with existing HTTP proxies, and requires less boilerplate.",
         "Highlight unidirectional data flow and standard HTTP proxy compatibility.", "junior"),
        ("Securing APIs against OWASP Top 10", "What are the most frequent API vulnerabilities in the OWASP API Top 10?",
         "The most critical is Broken Object Level Authorization (BOLA), where a user accesses another's resource by manipulating an ID in the URL. Others include Broken Authentication, Unrestricted Resource Consumption, and Mass Assignment.",
         "Emphasize BOLA/IDOR and object-level permission verification.", "mid"),
        ("Pagination: Offset vs Keyset (Cursor)", "Why should high-volume APIs adopt cursor-based pagination instead of offset and limit?",
         "Offset pagination requires the database to scan and discard rows (OFFSET 100000), resulting in O(n) slowdowns and duplicate/skipped items when new rows are inserted. Cursor pagination filters with WHERE id > cursor, delivering constant O(1) performance.",
         "Contrast scan overhead O(n) with indexed index lookups O(1).", "mid"),
        ("Handling Long-Running Tasks in HTTP APIs", "How should an API handle a report generation request that takes 2 minutes to calculate?",
         "The API should accept the request, enqueue a background task, and immediately return HTTP 202 Accepted with a task ID and a status poll URL (or WebSocket hook). Returning synchronous connections leads to gateway timeouts.",
         "Explain HTTP 202 Accepted and async task polling.", "junior"),
        ("Observability: Logs, Metrics, and Traces", "How do the three pillars of observability connect during distributed microservice troubleshooting?",
         "Metrics alert you that a problem exists (e.g. error rate spike). Traces pinpoint which microservice and internal function call is responsible. Logs provide the contextual detail and error message of why that specific execution failed.",
         "Connect the three pillars: detection -> localization -> root cause.", "senior"),
    ]
    for title, text, model, tips, diff in api_data:
        questions.append({
            "id": len(questions) + 1,
            "category": "apis",
            "difficulty": diff,
            "title": title,
            "text": text,
            "model_answer": model,
            "tips": tips
        })

    # 6. Teamwork, Agile & Communication (15 questions)
    team_data = [
        ("Handling Estimation Pressures", "How do you respond when management asks you to cut a 3-week estimation in half without changing scope?",
         "I explain that estimation reflects engineering complexity and testing requirements. Cutting calendar time arbitrarily introduces technical debt and defect risks. Instead, I propose scoping down to core MVP deliverables that can safely ship in that timeframe.",
         "Defend engineering rigor while offering pragmatic scope alternatives.", "mid"),
        ("Conducting Effective Code Reviews", "What principles guide your code reviews to ensure they are both rigorous and encouraging?",
         "I focus on architecture, test coverage, and security rather than cosmetic nitpicks (which should be automated via linters). I explain the 'why' behind suggestions, prefix non-blocking thoughts as 'nit:', and praise clever solutions.",
         "Emphasize constructive tone, automated linting, and focus on architecture.", "mid"),
        ("Managing Technical Debt in Agile Sprints", "How do you convince product managers to allocate sprint capacity for refactoring and tech debt?",
         "I frame technical debt in terms of business impact: degraded release velocity, higher bug defect rates, and customer churn risk. I advocate for allocating a consistent 15-20% of every sprint to refactoring and stability.",
         "Connect technical debt to velocity and product reliability metrics.", "senior"),
        ("Handling a Toxic or Uncooperative Team Member", "Describe how you navigate working with an engineer who dismisses peers' ideas and creates tension.",
         "I keep communication objective, documented, and focused strictly on code quality and project goals. I address friction early in private one-on-one conversations with empathy, and if unprofessional behavior persists, escalate constructively to leadership.",
         "Demonstrate emotional intelligence and professional boundaries.", "senior"),
        ("Running Effective Blameless Post-Mortems", "Why is a blameless culture critical for software reliability, and how do you foster it?",
         "Blameless culture recognizes that humans make mistakes when systems and safety guardrails permit them. If people fear punishment, they hide incidents. Fostering a blameless culture encourages transparent disclosure and systemic process fixes.",
         "Highlight psychological safety and systemic process hardening.", "senior"),
        ("Sprint Retrospectives that Drive Real Change", "How do you ensure sprint retrospectives don't degenerate into repetitive complaining sessions?",
         "I structure retrospectives around actionable outcomes: each retrospective should produce at most two high-priority action items with assigned owners and measurable check-in criteria for the following sprint.",
         "Focus on actionable ownership and measurable follow-up.", "junior"),
        ("Onboarding Remote Engineers", "What strategies make remote developer onboarding smooth and empowering in the first 30 days?",
         "I provide a comprehensive README with a single-command setup, assign an onboarding buddy for daily check-ins, maintain an architecture glossary, and assign a small, meaningful PR to be merged within their first 48 hours.",
         "Mention automated setups, buddy systems, and quick early wins.", "mid"),
        ("Pair Programming Effectively", "When is pair programming most beneficial, and how do you make it productive?",
         "Pair programming is most beneficial during complex architectural refactorings, production incident triages, and knowledge transfers. I structure it using the Driver/Navigator model and swap roles regularly to maintain focus.",
         "Explain Driver/Navigator roles and optimal use cases.", "junior"),
        ("Managing Interruptions and Focus Time", "How do you protect your flow state while remaining accessible for team emergencies?",
         "I batch asynchronous communications in dedicated intervals, use status indicators on Slack to signal deep work blocks, and establish clear criteria for what constitutes a genuine production emergency requiring an interrupt.",
         "Discuss time-blocking and asynchronous communication discipline.", "junior"),
        ("Writing Clear RFCs / Architectural Proposals", "What key sections belong in a Request for Comments (RFC) document for a major architectural change?",
         "An RFC should include: Problem Statement, Context & Goals, Non-Goals, Proposed Solution with Architecture Diagrams, Alternative Approaches Considered & Rejected, Trade-offs, Migration Plan, and Security Considerations.",
         "Mention Non-Goals, Alternatives Considered, and Migration Plans.", "senior"),
        ("Working with Junior Engineers", "How do you balance guiding a junior developer without micromanaging or solving the problem for them?",
         "I ask probing questions that guide their analytical thinking (e.g. 'What happens if this network call fails?'). I encourage them to formulate a hypothesis and test it, stepping in only to validate their direction or explain core concepts.",
         "Focus on Socratic guidance, autonomy, and conceptual growth.", "senior"),
        ("Balancing Speed vs Perfection", "How do you decide when software is 'good enough' to ship to production?",
         "Software is ready to ship when it solves the core user problem reliably, satisfies security and data integrity requirements, has test coverage for critical paths, and can be monitored and rolled back safely if issues arise.",
         "Balance pragmatic delivery with safety guardrails.", "mid"),
        ("Handling Shifting Priorities Mid-Sprint", "A stakeholder requests an urgent feature pivot halfway through a sprint. How do you respond?",
         "I evaluate the business urgency with the product owner. If the pivot is truly critical, I explain the trade-off: to pull new work into the active sprint, an equivalent amount of existing sprint scope must be returned to the backlog.",
         "Enforce the fundamental trade-off: scope in equals scope out.", "mid"),
        ("Giving Constructive Upward Feedback", "Have you ever needed to provide critical feedback to your manager or lead? How did you approach it?",
         "I requested a private 1-on-1, used the Situation-Behavior-Impact framework to present concrete examples without accusatory language, and focused on how adjusting the workflow would help the team meet our shared goals.",
         "Use the Situation-Behavior-Impact (SBI) framework.", "senior"),
        ("Celebrating Team Success and Morale", "How do you contribute to maintaining positive team morale during prolonged difficult milestones?",
         "I make recognition visible by publicly praising teammates' contributions in standups and Slack channels, organizing casual retro wind-downs, and keeping communication transparent about progress toward the finish line.",
         "Highlight peer recognition and positive reinforcement.", "junior"),
    ]
    for title, text, model, tips, diff in team_data:
        questions.append({
            "id": len(questions) + 1,
            "category": "teamwork",
            "difficulty": diff,
            "title": title,
            "text": text,
            "model_answer": model,
            "tips": tips
        })

    # 7. DevOps, Cloud & CI/CD (15 questions)
    devops_data = [
        ("Blue-Green vs Canary Deployments", "Explain the difference between Blue-Green and Canary deployment strategies.",
         "Blue-Green maintains two identical production environments; traffic is instantly switched 100% from Blue to Green once validated. Canary releases route a tiny percentage of live traffic (e.g. 2%) to the new version, monitoring error rates before rolling out gradually.",
         "Contrast instant all-at-once cutover with progressive percentage rollout.", "mid"),
        ("Container Orchestration with Kubernetes", "What problem does Kubernetes solve that Docker alone cannot handle in production?",
         "Docker manages containers on a single host. Kubernetes orchestrates multi-host clusters, providing automated rolling rollouts, horizontal auto-scaling, self-healing container restarts, service discovery, and declarative load balancing.",
         "Highlight multi-node clustering, self-healing, and declarative scaling.", "mid"),
        ("Infrastructure as Code (IaC)", "What are the advantages of managing cloud resources with Terraform or OpenTofu instead of manual console clicking?",
         "IaC provides version-controlled, auditable, and reproducible cloud environments. It eliminates configuration drift, enables code reviews on infrastructure changes, and allows spinning up identical staging and recovery environments in minutes.",
         "Mention version control, drift elimination, and reproducible environments.", "junior"),
        ("Zero-Downtime Rolling Updates", "How do you ensure an application running in Docker or Kubernetes achieves zero downtime during rolling deploys?",
         "I configure readiness and liveness probes properly. The orchestrator routes traffic to new pods only after readiness probes succeed, while old pods receive graceful termination signals (SIGTERM) with adequate connection draining time.",
         "Explain readiness/liveness probes and graceful connection draining.", "mid"),
        ("Secrets Management in Cloud Environments", "Why should secrets never be baked into Docker images, and how should they be injected securely?",
         "Baking secrets into images exposes them in registry layers, Git histories, and logs. Secrets should be injected at runtime from a dedicated secrets vault (like HashiCorp Vault or AWS Secrets Manager) using environment variables or encrypted volume mounts.",
         "Discuss image layer exposure and runtime injection from secret stores.", "junior"),
        ("Automated Rollback Strategies", "How do you design an automated CI/CD pipeline to rollback automatically on production failure?",
         "The deployment pipeline monitors APM error rates and health metrics for 5 minutes post-deploy. If HTTP 5xx errors spike above a predetermined threshold (e.g. 1%), the pipeline triggers an automated rollback to the previous stable release tag.",
         "Mention synthetic health monitoring and automated threshold triggers.", "senior"),
        ("Log Aggregation Architectures (ELK / Loki)", "Why do distributed microservices require centralized logging like Grafana Loki or Elasticsearch?",
         "In distributed systems, requests hop across dozens of ephemeral containers. Centralized logging aggregates logs into a searchable index, tagging each line with correlation IDs so engineers can trace a user's journey across all microservices.",
         "Highlight correlation IDs and ephemeral container life cycles.", "junior"),
        ("Site Reliability Engineering: SLI, SLO, and SLA", "Can you explain the relationship between SLIs, SLOs, and SLAs in production systems?",
         "An SLI (Service Level Indicator) is a real metric like latency or error rate. An SLO (Service Level Objective) is the internal target the team aims for, like 99.9% uptime. An SLA (Service Level Agreement) is the legal contract with customers with financial consequences if breached.",
         "Differentiate measurement (SLI), internal goal (SLO), and legal contract (SLA).", "senior"),
        ("Error Budgets in SRE", "What is an Error Budget and how does it balance development velocity against system stability?",
         "An Error Budget is the allowed unreliability of a service (e.g. 0.1% downtime for a 99.9% SLO). If the budget is intact, teams ship rapidly. If the error budget is exhausted by outages, feature releases freeze and effort shifts strictly to stability.",
         "Explain the balance between product velocity and reliability engineering.", "senior"),
        ("Continuous Profiling in Production", "What is continuous profiling (like Parca or Pyroscope) and why is it becoming standard in DevOps?",
         "Continuous profiling samples CPU and memory usage at low overhead directly in production, attributing resource costs to specific code functions. It allows spotting performance regressions and cloud cost inefficiencies that synthetic load tests miss.",
         "Mention low-overhead sampling and real-world workload profiling.", "senior"),
        ("Securing Container Images (SBOM & Scanning)", "How do you secure container images in a modern CI pipeline against known vulnerabilities?",
         "I use minimal base images like Alpine or distroless, avoid running containers as root, scan images with tools like Trivy or Grype in CI to block high/critical CVEs, and generate Software Bills of Materials (SBOM) for compliance.",
         "Mention minimal distroless bases, non-root users, and automated CVE scanners.", "mid"),
        ("Edge Caching and CDNs (Cloudflare / CloudFront)", "How does a Content Delivery Network reduce backend server load and improve international latency?",
         "A CDN caches static assets and cacheable dynamic API responses across a globally distributed network of edge servers (Points of Presence), terminating TLS and serving responses geographically close to users without hitting origin servers.",
         "Explain edge caching, TLS termination, and origin offloading.", "junior"),
        ("Chaos Engineering and Resilience Testing", "What is Chaos Engineering and why do companies like Netflix run Chaos Monkey in production?",
         "Chaos Engineering tests system resilience by deliberately injecting real failures—such as killing random nodes or injecting network latency—to verify that fallback mechanisms, auto-healing, and circuit breakers function as expected.",
         "Highlight proactive weakness discovery before organic outages happen.", "senior"),
        ("Database Backup & Disaster Recovery (RPO and RTO)", "What do Recovery Point Objective (RPO) and Recovery Time Objective (RTO) mean in disaster recovery?",
         "RPO defines the maximum acceptable data loss measured in time (e.g. 15 minutes of data). RTO defines the maximum acceptable downtime to restore operations (e.g. 1 hour). They guide backup frequency and failover infrastructure design.",
         "Contrast data loss window (RPO) with downtime duration (RTO).", "senior"),
        ("GitOps Workflows with ArgoCD", "What is GitOps and how does it improve Kubernetes cluster management?",
         "GitOps uses Git repositories as the single source of truth for declared infrastructure and application state. Automated reconciliation operators like ArgoCD continuously pull Git changes and synchronize the live cluster state automatically.",
         "Explain Git as the single source of truth and automated reconciliation loops.", "mid"),
    ]
    for title, text, model, tips, diff in devops_data:
        questions.append({
            "id": len(questions) + 1,
            "category": "devops",
            "difficulty": diff,
            "title": title,
            "text": text,
            "model_answer": model,
            "tips": tips
        })

    # 8. Portfolio & Past Projects (10 questions)
    portfolio_data = [
        ("Architectural Walkthrough of Your Best Project", "Can you walk me through the architecture of a project you are most proud of building?",
         "I built a self-hosted full-stack English training platform. The backend orchestrates Whisper for speech-to-text, Ollama for grammar evaluation, and Piper for neural TTS, with an asynchronous SQLite queue and a Flutter client with offline synchronization.",
         "Highlight technical autonomy, clean layer separation, and real problems solved.", "mid"),
        ("Overcoming a Major Technical Roadblock", "What was the most difficult technical roadblock you faced in a recent project, and how did you conquer it?",
         "We experienced browser audio decoding crashes when streaming raw TTS responses on the web. I traced the issue to attachment headers forcing downloads instead of inline byte-range streaming, patched the headers, and verified with automated browser sessions.",
         "Use the STAR method: Situation, Task, Action, and Quantifiable Result.", "mid"),
        ("Selecting Your Tech Stack", "How did you choose the technologies for your latest application? What alternatives did you reject?",
         "I chose FastAPI for its native async support and automatic OpenAPI documentation, paired with Flutter for cross-platform web and mobile UI. I considered Next.js, but Flutter provided stronger offline capabilities and unified state management.",
         "Explain objective criteria (performance, developer velocity, platform constraints).", "junior"),
        ("Testing Strategy in Your Portfolio", "How did you structure tests in your personal projects to ensure high confidence without excessive maintenance?",
         "I adhered to the testing pyramid: comprehensive unit tests for core domain logic and data parsing, API integration tests validating HTTP contracts and status codes, and widget tests verifying state transitions under mock providers.",
         "Demonstrate disciplined testing methodology even on personal projects.", "junior"),
        ("Scaling a Personal Project", "If your current application suddenly scaled to 100,000 daily active users, what would break first and how would you adapt it?",
         "The local SQLite database and single-threaded TTS inference would saturate. I would migrate to PostgreSQL with read replicas, offload CPU-heavy audio synthesis to a worker pool via RabbitMQ or Celery, and put Cloudflare edge caching in front.",
         "Demonstrate architectural foresight and capacity planning.", "senior"),
        ("Handling User Feedback and Iteration", "Tell me about a feature in your project that evolved significantly based on real user feedback.",
         "Initially, the app displayed full Spanish translations immediately, but users reported it hampered English immersion. I redesigned the UI to hide Spanish hints behind an explicit reveal toggle and added phonetic IPA guides.",
         "Show user empathy and willingness to iterate based on evidence.", "junior"),
        ("Ensuring Security and Data Privacy", "How do you protect sensitive user credentials and data in your client applications?",
         "I store API tokens and encryption keys in platform-native secure enclaves via flutter_secure_storage, enforce TLS, sanitize user inputs against injection attacks, and exclude environment secrets from version control.",
         "Mention hardware-backed secure storage and secure data pipelines.", "mid"),
        ("Optimizing Performance on Low-End Devices", "What profiling and optimizations did you perform to keep your app snappy on mobile and web?",
         "I isolated high-frequency repaints using RepaintBoundary widgets, implemented lazy list view rendering, tree-shook unused icon fonts, and compressed audio payloads, maintaining smooth 60fps animations.",
         "Demonstrate hands-on profiling experience with real metrics.", "mid"),
        ("Open-Source Contributions and Collaboration", "Have you contributed to open-source libraries or learned from community codebases?",
         "Yes, I frequently inspect open-source implementations to understand idioms—such as examining the official py-fsrs spaced repetition algorithm and exploring Flutter community plugins to benchmark architectural patterns.",
         "Show curiosity and respect for the broader engineering ecosystem.", "junior"),
        ("Lessons Learned from a Scrapped Feature", "Tell me about a feature or prototype you decided to discard, and what you learned from it.",
         "I prototyped a complex multi-layered audio waveform visualizer, but it consumed excessive battery on mobile devices. I replaced it with a sleek, low-overhead pulsing amplitude indicator, learning that simplicity often outperforms complexity.",
         "Show maturity, resource awareness, and willingness to kill darlings.", "mid"),
    ]
    for title, text, model, tips, diff in portfolio_data:
        questions.append({
            "id": len(questions) + 1,
            "category": "portfolio",
            "difficulty": diff,
            "title": title,
            "text": text,
            "model_answer": model,
            "tips": tips
        })

    # 9. Internships & Early Career (10 questions)
    intern_data = [
        ("Quickly Getting Up to Speed", "As an entry-level engineer or intern, what is your strategy for ramping up on a massive production codebase?",
         "I start by running the project locally, exploring the unit tests to see how modules behave, drawing a high-level component diagram, and tackling a well-scoped bug in my first week to learn the deployment pipeline.",
         "Show proactive initiative, structured learning, and humbleness.", "junior"),
        ("Knowing When to Ask for Help", "How long do you struggle with a technical blocker before asking a senior colleague for guidance?",
         "I follow the 30-minute rule: I spend 30 minutes researching, checking logs, and formulating hypotheses. If I am still stuck, I approach a senior teammate with a clear summary of what I tried, what happened, and my specific question.",
         "Demonstrate respect for senior engineers' time while avoiding being stuck.", "junior"),
        ("Managing Academic Knowledge vs Production Reality", "How do you adapt textbook software concepts to real-world code that may not follow ideal design patterns?",
         "Textbooks teach idealized patterns, but production code balances legacy constraints and delivery deadlines. I adapt by understanding why existing trade-offs were made before proposing incremental refactoring.",
         "Show flexibility, pragmatic mindset, and respect for existing code.", "junior"),
        ("Receiving Tough Feedback During Evaluations", "Tell me about critical feedback you received during an internship or project review and how you adapted.",
         "My mentor noted that my commit messages were too brief and lacked context. I adopted the Conventional Commits standard, writing detailed descriptions of the 'why' behind changes, which improved team collaboration.",
         "Demonstrate openness to feedback and immediate behavioral correction.", "junior"),
        ("Balancing Depth vs Breadth in Tech", "As you start your engineering career, how do you balance mastering one language versus learning multiple tools?",
         "I adopt a T-shaped learning approach: deep mastery of one backend stack (like Python/FastAPI) and clean software fundamentals, combined with broad working familiarity with frontend frameworks, Docker, and databases.",
         "Articulate the T-shaped engineer philosophy.", "junior"),
        ("Participating in Daily Standups", "What makes a daily standup update concise, valuable, and non-repetitive?",
         "A great standup update is focused: what I accomplished yesterday that matters to the team, what I am delivering today, and an immediate callout of any blockers that require assistance.",
         "Keep it brief, focused on team impact, and highlight blockers.", "junior"),
        ("Taking Responsibility for Bugs in Production", "Imagine a commit you merged breaks an internal tool used by the operations team. What do you do?",
         "I immediately notify the operations team, revert the offending commit or push a hotfix, verify the tool is operational again, and then write a test case so the bug cannot happen again.",
         "Show responsibility, rapid communication, and post-fix testing.", "junior"),
        ("Staying Curious and Learning Outside Work", "How do you stay updated with emerging technologies and industry best practices?",
         "I read engineering blogs from companies like Netflix and Uber, listen to podcasts like Talk Python To Me and Hard Fork, build weekend proofs of concept, and study curated open-source repositories.",
         "Demonstrate passion, continuous learning, and curiosity.", "junior"),
        ("Effective Written Documentation", "Why is documentation crucial for an engineering team, and what is your approach to writing it?",
         "Code explains 'how', but documentation explains 'why'. I document architectural decisions, API contracts, and troubleshooting runbooks with clear steps and code snippets so anyone can reproduce the workflow.",
         "Emphasize the 'why' behind architectural choices.", "junior"),
        ("What Excites You Most About Software Engineering", "Why did you choose software development as your career path?",
         "I love the power of turning abstract ideas into real, tangible tools that solve genuine human problems. The rapid feedback loop of writing code, testing it, and seeing immediate impact is deeply satisfying.",
         "Speak with genuine enthusiasm, authenticity, and passion.", "junior"),
    ]
    for title, text, model, tips, diff in intern_data:
        questions.append({
            "id": len(questions) + 1,
            "category": "internships",
            "difficulty": diff,
            "title": title,
            "text": text,
            "model_answer": model,
            "tips": tips
        })

    return questions

def main():
    base_dir = os.path.dirname(__file__)
    seed_dir = base_dir
    os.makedirs(seed_dir, exist_ok=True)
    
    questions = build_interview_questions()
    q_file = os.path.join(seed_dir, "questions.json")
    with open(q_file, "w", encoding="utf-8") as f:
        json.dump(questions, f, indent=2, ensure_ascii=False)
    print(f"Generated {len(questions)} interview questions in {q_file}")

if __name__ == "__main__":
    main()
