class GrammarQuestion {
  final int id;
  final String level;
  final String unitTitle;
  final String prompt;
  final String? contextSentence;
  final List<String> options;
  final String correctAnswer;
  final String spanishExplanation;
  final String audioText;

  const GrammarQuestion({
    required this.id,
    required this.level,
    required this.unitTitle,
    required this.prompt,
    this.contextSentence,
    required this.options,
    required this.correctAnswer,
    required this.spanishExplanation,
    required this.audioText,
  });

  factory GrammarQuestion.fromJson(Map<String, dynamic> j) => GrammarQuestion(
        id: j['id'] as int,
        level: j['level'] as String,
        unitTitle: j['unitTitle'] as String,
        prompt: j['prompt'] as String,
        contextSentence: j['contextSentence'] as String?,
        options: List<String>.from(j['options']),
        correctAnswer: j['correctAnswer'] as String,
        spanishExplanation: j['spanishExplanation'] as String,
        audioText: j['audioText'] as String,
      );
}

class GrammarUnit {
  final String id;
  final String level;
  final String title;
  final String tag;
  final String subtitle;
  final String ruleSummary;
  final List<Map<String, String>> comparisonExamples;
  final List<GrammarQuestion> questions;

  const GrammarUnit({
    required this.id,
    required this.level,
    required this.title,
    required this.tag,
    required this.subtitle,
    required this.ruleSummary,
    required this.comparisonExamples,
    required this.questions,
  });

  factory GrammarUnit.fromJson(Map<String, dynamic> j) => GrammarUnit(
        id: j['id'] as String,
        level: j['level'] as String,
        title: j['title'] as String,
        tag: j['tag'] as String,
        subtitle: j['subtitle'] as String,
        ruleSummary: j['ruleSummary'] as String,
        comparisonExamples: List<Map<String, String>>.from((j['comparisonExamples'] as List).map((x) => Map<String, String>.from(x))),
        questions: List<GrammarQuestion>.from(
          (j['questions'] as List).map((x) {
            final qMap = Map<String, dynamic>.from(x);
            qMap['level'] ??= j['level'];
            qMap['unitTitle'] ??= j['title'];
            return GrammarQuestion.fromJson(qMap);
          }),
        ),
      );
}

final List<GrammarUnit> allGrammarUnits = [
  const GrammarUnit(
    id: "unit-1-junior",
    level: "Level 1: Junior",
    title: "Unit 1: Past Simple in STAR Stories",
    tag: "A1 - A2",
    subtitle: "C\u00f3mo narrar tus proyectos y bugs pasados con precisi\u00f3n temporal",
    ruleSummary: "En entrevistas, usa SIEMPRE Past Simple (built, refactored, resolved) para eventos en un momento espec\u00edfico del pasado (ej. 'in 2023', 'last quarter'). Usa Present Perfect (have worked) SOLAMENTE para experiencias sin fecha o que siguen activas hoy.",
    comparisonExamples: [
      {
        'wrong': "In 2023, I have redesigned our payment microservice.",
        'right': "In 2023, I redesigned our payment microservice.",
        'tip': "Una fecha concreta en el pasado (2023) exige Past Simple.",
      },
      {
        'wrong': "I work at this company since two years.",
        'right': "I have been working at this company for two years.",
        'tip': "Para estados continuados hasta hoy, usa Present Perfect Continuous con 'for'.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 101,
        level: "Level 1: Junior",
        unitTitle: "Unit 1: Past Simple in STAR Stories",
        prompt: "When our Redis cluster crashed last month, I _____ the traffic to the fallback replica.",
        contextSentence: "STAR Situation/Action: Specific past event (last month).",
        options: ["have rerouted", "rerouted", "am rerouting", "had reroute"],
        correctAnswer: "rerouted",
        spanishExplanation: "Con 'last month' (fecha espec\u00edfica), la regla exige Past Simple ('rerouted').",
        audioText: "When our Redis cluster crashed last month, I rerouted the traffic to the fallback replica.",
      ),
      GrammarQuestion(
        id: 102,
        level: "Level 1: Junior",
        unitTitle: "Unit 1: Past Simple in STAR Stories",
        prompt: "Throughout my career, I _____ distributed backends in Python and Go.",
        contextSentence: "General career experience with no specific past timestamp.",
        options: ["built", "have built", "was building", "builded"],
        correctAnswer: "have built",
        spanishExplanation: "'Throughout my career' expresa experiencia acumulada; requiere Present Perfect.",
        audioText: "Throughout my career, I have built distributed backends in Python and Go.",
      ),
      GrammarQuestion(
        id: 103,
        level: "Level 1: Junior",
        unitTitle: "Unit 1: Past Simple in STAR Stories",
        prompt: "Yesterday the QA engineer _____ a critical memory leak in the parser.",
        contextSentence: "Specific completed time marker: Yesterday.",
        options: ["has identified", "identified", "is identifying", "identifies"],
        correctAnswer: "identified",
        spanishExplanation: "'Yesterday' exige Past Simple ('identified'). Nunca 'has identified' con marcadores cerrados.",
        audioText: "Yesterday the QA engineer identified a critical memory leak in the parser.",
      ),
      GrammarQuestion(
        id: 104,
        level: "Level 1: Junior",
        unitTitle: "Unit 1: Past Simple in STAR Stories",
        prompt: "We _____ that legacy monolithic repository for over three years now.",
        contextSentence: "Ongoing activity starting in the past and continuing today.",
        options: ["maintained", "have been maintaining", "maintain", "were maintaining"],
        correctAnswer: "have been maintaining",
        spanishExplanation: "'For over three years now' indica acci\u00f3n continuada hasta hoy (Present Perfect Continuous).",
        audioText: "We have been maintaining that legacy monolithic repository for over three years now.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-2-junior",
    level: "Level 1: Junior",
    title: "Unit 2: Describing Daily Tasks & Standups",
    tag: "A1 - A2",
    subtitle: "Present Simple vs Present Continuous en tus ceremonias \u00e1giles",
    ruleSummary: "Usa Present Continuous ('I am currently investigating the timeout') para lo que est\u00e1s haciendo hoy o en este sprint. Usa Present Simple ('I maintain the billing API') para responsabilidades y rutinas permanentes.",
    comparisonExamples: [
      {
        'wrong': "Today I work on the database indexing.",
        'right': "Today I am working on the database indexing.",
        'tip': "Las tareas temporales en progreso se expresan en Present Continuous.",
      },
      {
        'wrong': "Every morning I am checking server alerts.",
        'right': "Every morning I check server alerts.",
        'tip': "Rutinas diarias repetitivas se expresan en Present Simple.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 105,
        level: "Level 1: Junior",
        unitTitle: "Unit 2: Describing Daily Tasks & Standups",
        prompt: "In today's standup, I reported that I _____ the OAuth token expiration bug.",
        contextSentence: "Activity currently in progress this morning.",
        options: ["investigate", "am currently investigating", "investigated", "have investigate"],
        correctAnswer: "am currently investigating",
        spanishExplanation: "Para tareas en curso durante el d\u00eda de trabajo se usa 'am currently investigating'.",
        audioText: "In today's standup, I reported that I am currently investigating the OAuth token expiration bug.",
      ),
      GrammarQuestion(
        id: 106,
        level: "Level 1: Junior",
        unitTitle: "Unit 2: Describing Daily Tasks & Standups",
        prompt: "Our engineering squad usually _____ a sprint planning session every other Monday.",
        contextSentence: "Recurring team routine.",
        options: ["is holding", "holds", "held", "has hold"],
        correctAnswer: "holds",
        spanishExplanation: "'Usually' indica h\u00e1bito peri\u00f3dico recurrente; exige Present Simple ('holds').",
        audioText: "Our engineering squad usually holds a sprint planning session every other Monday.",
      ),
      GrammarQuestion(
        id: 107,
        level: "Level 1: Junior",
        unitTitle: "Unit 2: Describing Daily Tasks & Standups",
        prompt: "Right now, the front-end team _____ the design system to Material 3.",
        contextSentence: "Temporary sprint migration in progress.",
        options: ["migrates", "is migrating", "migrated", "was migrate"],
        correctAnswer: "is migrating",
        spanishExplanation: "'Right now' exige Present Continuous ('is migrating').",
        audioText: "Right now, the front-end team is migrating the design system to Material 3.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-3-junior",
    level: "Level 1: Junior",
    title: "Unit 3: Prepositions of Tech (In, On, At)",
    tag: "A1 - A2",
    subtitle: "Dominio de ubicaciones t\u00e9cnicas: in memory, on the server, at runtime",
    ruleSummary: "Usa 'IN' para contenedores, lenguajes y almacenes internos ('in Python', 'in memory', 'in the database'). Usa 'ON' para plataformas, servidores y puertos ('on AWS', 'on the server', 'on port 8080'). Usa 'AT' para momentos y fases ('at runtime', 'at startup').",
    comparisonExamples: [
      {
        'wrong': "The application crashes in runtime.",
        'right': "The application crashes at runtime.",
        'tip': "Las fases de ejecuci\u00f3n usan la preposici\u00f3n 'at' (at runtime, at compile time).",
      },
      {
        'wrong': "We host our microservices in AWS.",
        'right': "We host our microservices on AWS.",
        'tip': "Las plataformas y proveedores de nube usan 'on' (on AWS, on GCP).",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 108,
        level: "Level 1: Junior",
        unitTitle: "Unit 3: Prepositions of Tech (In, On, At)",
        prompt: "We store session tokens _____ memory using an encrypted Redis cache.",
        contextSentence: "Internal container storage.",
        options: ["on", "in", "at", "by"],
        correctAnswer: "in",
        spanishExplanation: "El almacenamiento interno de datos se expresa como 'in memory'.",
        audioText: "We store session tokens in memory using an encrypted Redis cache.",
      ),
      GrammarQuestion(
        id: 109,
        level: "Level 1: Junior",
        unitTitle: "Unit 3: Prepositions of Tech (In, On, At)",
        prompt: "The background daemon listens for webhook events _____ port 443.",
        contextSentence: "Network port configuration.",
        options: ["in", "on", "at", "to"],
        correctAnswer: "on",
        spanishExplanation: "La escucha en puertos de red se formula siempre como 'on port X'.",
        audioText: "The background daemon listens for webhook events on port 443.",
      ),
      GrammarQuestion(
        id: 110,
        level: "Level 1: Junior",
        unitTitle: "Unit 3: Prepositions of Tech (In, On, At)",
        prompt: "Environment variables are loaded _____ startup to configure database connections.",
        contextSentence: "Process lifecycle phase.",
        options: ["at", "in", "on", "during of"],
        correctAnswer: "at",
        spanishExplanation: "Las fases del ciclo de vida de un proceso usan 'at' ('at startup', 'at runtime').",
        audioText: "Environment variables are loaded at startup to configure database connections.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-4-junior",
    level: "Level 1: Junior",
    title: "Unit 4: Reporting Bugs & Concordance",
    tag: "A1 - A2",
    subtitle: "Concordancia sujeto-verbo en m\u00e9tricas y datos: 'data is/are', 'each', 'none'",
    ruleSummary: "En ingl\u00e9s t\u00e9cnico moderno, 'data' suele tratarse como incontable singular ('the data shows'). Sujetos como 'Each service' o 'Neither cluster' son estrictamente singulares ('each service has its own DB').",
    comparisonExamples: [
      {
        'wrong': "Each of the microservices have a health check endpoint.",
        'right': "Each of the microservices has a health check endpoint.",
        'tip': "'Each' es singular y rige verbo en tercera persona ('has').",
      },
      {
        'wrong': "The telemetry data show high memory usage.",
        'right': "The telemetry data shows high memory usage.",
        'tip': "En la pr\u00e1ctica de ingenier\u00eda de software, 'data' funciona como un sustantivo colectivo singular.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 111,
        level: "Level 1: Junior",
        unitTitle: "Unit 4: Reporting Bugs & Concordance",
        prompt: "Each of our worker nodes _____ a local copy of the machine learning model.",
        contextSentence: "Distributed architecture node configuration.",
        options: ["maintain", "maintains", "are maintaining", "have maintained"],
        correctAnswer: "maintains",
        spanishExplanation: "'Each' toma verbo en singular de tercera persona ('maintains').",
        audioText: "Each of our worker nodes maintains a local copy of the machine learning model.",
      ),
      GrammarQuestion(
        id: 112,
        level: "Level 1: Junior",
        unitTitle: "Unit 4: Reporting Bugs & Concordance",
        prompt: "Telemetry metrics indicate that the collected data _____ anomalous latency spikes.",
        contextSentence: "Log analysis.",
        options: ["exhibits", "exhibit", "are exhibiting", "have exhibit"],
        correctAnswer: "exhibits",
        spanishExplanation: "'Data' en software corporativo se conjuga en singular ('exhibits').",
        audioText: "Telemetry metrics indicate that the collected data exhibits anomalous latency spikes.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-5-junior",
    level: "Level 1: Junior",
    title: "Unit 5: Technical Questions in Interviews",
    tag: "A1 - A2",
    subtitle: "Inversi\u00f3n y auxiliares para formular preguntas inteligentes al entrevistador",
    ruleSummary: "Para preguntar sobre el stack o retos t\u00e9cnicos del equipo, invierte el auxiliar: 'How does your team handle tech debt?' (nunca 'How your team handles?'). Para preguntas indirectas educadas usa: 'Could you tell me how the team approaches testing?'",
    comparisonExamples: [
      {
        'wrong': "How your deployment pipeline works?",
        'right': "How does your deployment pipeline work?",
        'tip': "Las preguntas directas en Present Simple requieren el auxiliar 'does' + infinitivo.",
      },
      {
        'wrong': "Could you tell me how does the on-call rotation work?",
        'right': "Could you tell me how the on-call rotation works?",
        'tip': "En preguntas indirectas no hay inversi\u00f3n auxiliar; el orden vuelve a ser sujeto + verbo.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 113,
        level: "Level 1: Junior",
        unitTitle: "Unit 5: Technical Questions in Interviews",
        prompt: "Could you tell me how your engineering team _____ production incidents?",
        contextSentence: "Polite indirect question to interviewer.",
        options: ["does handle", "handles", "is handling", "did handle"],
        correctAnswer: "handles",
        spanishExplanation: "En preguntas indirectas ('Could you tell me how...'), no se usa 'does'; el verbo va directo en presente ('handles').",
        audioText: "Could you tell me how your engineering team handles production incidents?",
      ),
      GrammarQuestion(
        id: 114,
        level: "Level 1: Junior",
        unitTitle: "Unit 5: Technical Questions in Interviews",
        prompt: "What observability tools _____ currently use to track microservice latency?",
        contextSentence: "Direct technical question.",
        options: ["do you", "you do", "are you to", "did you used to"],
        correctAnswer: "do you",
        spanishExplanation: "La pregunta directa requiere 'do you' antes del verbo principal.",
        audioText: "What observability tools do you currently use to track microservice latency?",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-6-junior",
    level: "Level 1: Junior",
    title: "Unit 6: Passive Voice in Incident Reports",
    tag: "A1 - A2",
    subtitle: "C\u00f3mo redactar post-mortems sin culpar a personas individuales",
    ruleSummary: "En ingenier\u00eda de software libre de culpa (blameless post-mortem), la voz pasiva es fundamental: 'The configuration was updated without validation' en lugar de 'John broke production'. Estructura: Sujeto + was/were + participio.",
    comparisonExamples: [
      {
        'wrong': "The backend was crash by the bad query.",
        'right': "The backend was crashed by the unindexed query.",
        'tip': "Usa el participio correcto del verbo en la pasiva.",
      },
      {
        'wrong': "Carlos pushed buggy code to main.",
        'right': "An unverified pull request was merged into the main branch.",
        'tip': "Enfoca la acci\u00f3n en el objeto del incidente, no en la persona.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 115,
        level: "Level 1: Junior",
        unitTitle: "Unit 6: Passive Voice in Incident Reports",
        prompt: "During the outage, the primary database instance _____ automatically to the secondary zone.",
        contextSentence: "Failover mechanism post-mortem.",
        options: ["was failed over", "failed over", "is fail over", "was failing"],
        correctAnswer: "was failed over",
        spanishExplanation: "Voz pasiva en pasado ('was failed over') para describir el proceso ejecutado por el orquestador.",
        audioText: "During the outage, the primary database instance was failed over automatically to the secondary zone.",
      ),
      GrammarQuestion(
        id: 116,
        level: "Level 1: Junior",
        unitTitle: "Unit 6: Passive Voice in Incident Reports",
        prompt: "All corrupted cache entries _____ within fifteen minutes of the initial alert.",
        contextSentence: "Incident remediation report.",
        options: ["were invalidated", "was invalidated", "invalidated", "have been invalidate"],
        correctAnswer: "were invalidated",
        spanishExplanation: "'Entries' es plural, por lo que exige 'were invalidated'.",
        audioText: "All corrupted cache entries were invalidated within fifteen minutes of the initial alert.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-7-junior",
    level: "Level 1: Junior",
    title: "Unit 7: Essential Phrasal Verbs in Code",
    tag: "A1 - A2",
    subtitle: "Spin up, roll back, tear down, scale out: verbos frasales indispensables",
    ruleSummary: "Los ingenieros nativos usan phrasal verbs en el 70% de las conversaciones cotidianas: 'spin up a container' (arrancar), 'roll back a release' (revertir), 'tear down test infra' (destruir), 'scale out' (escalar horizontalmente).",
    comparisonExamples: [
      {
        'wrong': "We returned the release to the previous version.",
        'right': "We rolled back the release immediately.",
        'tip': "'Roll back' es el est\u00e1ndar t\u00e9cnico indiscutible para revertir despliegues.",
      },
      {
        'wrong': "I opened a new Docker container.",
        'right': "I spun up a new Docker container.",
        'tip': "Usa 'spin up' para creaci\u00f3n y arranque din\u00e1mico de entornos.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 117,
        level: "Level 1: Junior",
        unitTitle: "Unit 7: Essential Phrasal Verbs in Code",
        prompt: "When the canary release showed a 5% error rate, we immediately _____ the deployment.",
        contextSentence: "Continuous delivery rollback.",
        options: ["rolled back", "spun up", "tore down", "scaled out"],
        correctAnswer: "rolled back",
        spanishExplanation: "'Rolled back' significa revertir a una versi\u00f3n previa ante errores.",
        audioText: "When the canary release showed a 5% error rate, we immediately rolled back the deployment.",
      ),
      GrammarQuestion(
        id: 118,
        level: "Level 1: Junior",
        unitTitle: "Unit 7: Essential Phrasal Verbs in Code",
        prompt: "Our CI pipeline automatically _____ temporary testing environments after PR approval.",
        contextSentence: "Infrastructure automation.",
        options: ["tears down", "rolls back", "drills down", "falls back"],
        correctAnswer: "tears down",
        spanishExplanation: "'Tear down' significa desmantelar o destruir recursos temporales.",
        audioText: "Our CI pipeline automatically tears down temporary testing environments after PR approval.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-8-junior",
    level: "Level 1: Junior",
    title: "Unit 8: Modals for Permissions & Capabilities",
    tag: "A1 - A2",
    subtitle: "Can, May, Must, Should en especificaciones de APIs y requerimientos",
    ruleSummary: "RFC 2119 define el lenguaje t\u00e9cnico oficial: 'MUST' (obligatorio sin excepci\u00f3n), 'SHOULD' (recomendado con justificaci\u00f3n si se omite), 'MAY' (opcional), 'CAN' (capacidad t\u00e9cnica del sistema).",
    comparisonExamples: [
      {
        'wrong': "Clients must optional send an API key.",
        'right': "Clients may optionally send an API key.",
        'tip': "'May' expresa opcionalidad o permiso; 'must' es obligatorio.",
      },
      {
        'wrong': "The microservice can to handle 10k requests.",
        'right': "The microservice can handle 10k requests.",
        'tip': "Los verbos modales van siempre seguidos de infinitivo sin 'to'.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 119,
        level: "Level 1: Junior",
        unitTitle: "Unit 8: Modals for Permissions & Capabilities",
        prompt: "In accordance with OAuth standards, the client _____ include a valid bearer token in the Authorization header.",
        contextSentence: "Mandatory security requirement.",
        options: ["must", "may", "can to", "might optionally"],
        correctAnswer: "must",
        spanishExplanation: "Un requisito ineludible de seguridad se formula con 'must'.",
        audioText: "In accordance with OAuth standards, the client must include a valid bearer token in the Authorization header.",
      ),
      GrammarQuestion(
        id: 120,
        level: "Level 1: Junior",
        unitTitle: "Unit 8: Modals for Permissions & Capabilities",
        prompt: "Under heavy burst traffic, our autoscaler _____ spawn up to fifty replica pods.",
        contextSentence: "Technical capability.",
        options: ["can", "should to", "ought", "must to"],
        correctAnswer: "can",
        spanishExplanation: "'Can' expresa capacidad t\u00e9cnica del sistema sin part\u00edcula 'to'.",
        audioText: "Under heavy burst traffic, our autoscaler can spawn up to fifty replica pods.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-9-mid",
    level: "Level 2: Mid-Level",
    title: "Unit 2: System Conditionals & Projections",
    tag: "B1 - B2",
    subtitle: "C\u00f3mo formular hip\u00f3tesis de escalabilidad y justificar decisiones t\u00e9cnicas",
    ruleSummary: "Usa Primer Condicional (If + Present Simple, will + Verb) para predicciones t\u00e9cnicas realistas. Usa Segundo Condicional (If + Past Simple, would + Verb) para escenarios hipot\u00e9ticos de arquitectura ('If we used Cassandra, we would achieve...').",
    comparisonExamples: [
      {
        'wrong': "If we will add a cache, the database will be faster.",
        'right': "If we add a cache, the database will be faster.",
        'tip': "En la cl\u00e1usula con 'If', NUNCA pongas 'will'. Usa Present Simple.",
      },
      {
        'wrong': "If we migrated to microservices, we will solve all bugs.",
        'right': "If we migrated to microservices, we would face distributed tracing challenges.",
        'tip': "El segundo condicional usa 'would', no 'will'.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 201,
        level: "Level 2: Mid-Level",
        unitTitle: "Unit 2: System Conditionals & Projections",
        prompt: "If we _____ write-heavy workloads to Kafka, the primary database latency will drop by 40%.",
        contextSentence: "Realistic system projection (First Conditional).",
        options: ["offload", "will offload", "would offload", "offloaded"],
        correctAnswer: "offload",
        spanishExplanation: "En la cl\u00e1usula 'If' del primer condicional se usa Present Simple ('offload'), nunca 'will'.",
        audioText: "If we offload write-heavy workloads to Kafka, the primary database latency will drop by 40%.",
      ),
      GrammarQuestion(
        id: 202,
        level: "Level 2: Mid-Level",
        unitTitle: "Unit 2: System Conditionals & Projections",
        prompt: "If we switched from REST to gRPC, we _____ payload serialization overhead dramatically.",
        contextSentence: "Hypothetical architecture evaluation (Second Conditional).",
        options: ["will reduce", "would reduce", "reduced", "reduce"],
        correctAnswer: "would reduce",
        spanishExplanation: "La condici\u00f3n hipot\u00e9tica en pasado ('switched') rige 'would reduce' en la cl\u00e1usula principal.",
        audioText: "If we switched from REST to gRPC, we would reduce payload serialization overhead dramatically.",
      ),
      GrammarQuestion(
        id: 203,
        level: "Level 2: Mid-Level",
        unitTitle: "Unit 2: System Conditionals & Projections",
        prompt: "Unless we _____ strict connection pooling, the Postgres database will exhaust available file descriptors.",
        contextSentence: "System constraint with 'Unless' (= If not).",
        options: ["enforce", "will enforce", "enforced", "don't enforce"],
        correctAnswer: "enforce",
        spanishExplanation: "'Unless' ya incluye la negaci\u00f3n y act\u00faa como 'If'; requiere presente ('enforce').",
        audioText: "Unless we enforce strict connection pooling, the Postgres database will exhaust available file descriptors.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-10-mid",
    level: "Level 2: Mid-Level",
    title: "Unit 10: Present Perfect with 'Since' & 'For'",
    tag: "B1 - B2",
    subtitle: "Evoluci\u00f3n hist\u00f3rica de repositorios y stacks tecnol\u00f3gicos",
    ruleSummary: "'Since' marca el punto de inicio espec\u00edfico en el tiempo ('since 2021', 'since the last major refactor'). 'For' mide la duraci\u00f3n o per\u00edodo de tiempo transcurrido ('for three years', 'for several sprints').",
    comparisonExamples: [
      {
        'wrong': "We use Kubernetes since two years.",
        'right': "We have been using Kubernetes for two years.",
        'tip': "Usa Present Perfect Continuous con 'for' para duraciones acumuladas.",
      },
      {
        'wrong': "The service has been stable for the v2 launch.",
        'right': "The service has been stable since the v2 launch.",
        'tip': "Un hito puntual de inicio en el pasado requiere 'since'.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 204,
        level: "Level 2: Mid-Level",
        unitTitle: "Unit 10: Present Perfect with 'Since' & 'For'",
        prompt: "Our engineering department _____ using event sourcing _____ early 2022.",
        contextSentence: "Architecture adoption history.",
        options: ["has been / since", "is / for", "was / since", "have been / for"],
        correctAnswer: "has been / since",
        spanishExplanation: "Acci\u00f3n continua hasta el presente con hito temporal de inicio espec\u00edfico: 'has been / since'.",
        audioText: "Our engineering department has been using event sourcing since early 2022.",
      ),
      GrammarQuestion(
        id: 205,
        level: "Level 2: Mid-Level",
        unitTitle: "Unit 10: Present Perfect with 'Since' & 'For'",
        prompt: "The batch processing pipeline has operated without any downtime _____ over six consecutive months.",
        contextSentence: "Duration measurement.",
        options: ["for", "since", "during", "from"],
        correctAnswer: "for",
        spanishExplanation: "Un intervalo de tiempo de duraci\u00f3n ('over six consecutive months') exige 'for'.",
        audioText: "The batch processing pipeline has operated without any downtime for over six consecutive months.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-11-mid",
    level: "Level 2: Mid-Level",
    title: "Unit 11: Cause & Effect Connectors in RCA",
    tag: "B1 - B2",
    subtitle: "Due to, As a result, Consequently, Therefore en an\u00e1lisis de causa ra\u00edz",
    ruleSummary: "'Due to' va seguido de un sustantivo o frase sustantiva ('due to a memory leak'). 'Consequently' y 'As a result' conectan oraciones completas y van seguidos de coma ('Consequently, the server crashed').",
    comparisonExamples: [
      {
        'wrong': "Due to the memory leaked, the process crashed.",
        'right': "Due to the memory leak, the process crashed.",
        'tip': "'Due to' rige un sustantivo, no una cl\u00e1usula verbal completa.",
      },
      {
        'wrong': "The node failed because of it had no disk space.",
        'right': "The node failed because it had no disk space.",
        'tip': "'Because' introduce oraciones completas (sujeto + verbo); 'because of' rige sustantivos.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 206,
        level: "Level 2: Mid-Level",
        unitTitle: "Unit 11: Cause & Effect Connectors in RCA",
        prompt: "The query timed out _____ an unindexed foreign key in the orders table.",
        contextSentence: "Root cause explanation.",
        options: ["due to", "because", "consequently", "as a result"],
        correctAnswer: "due to",
        spanishExplanation: "Delante de una frase nominal ('an unindexed foreign key') se usa 'due to'.",
        audioText: "The query timed out due to an unindexed foreign key in the orders table.",
      ),
      GrammarQuestion(
        id: 207,
        level: "Level 2: Mid-Level",
        unitTitle: "Unit 11: Cause & Effect Connectors in RCA",
        prompt: "The microservice failed its health checks. _____, Kubernetes routed all live traffic away.",
        contextSentence: "Sentence-level cause and consequence.",
        options: ["Consequently", "Due to", "Owing to", "Because of"],
        correctAnswer: "Consequently",
        spanishExplanation: "Para abrir una nueva oraci\u00f3n introduciendo la consecuencia l\u00f3gica se usa 'Consequently,'.",
        audioText: "The microservice failed its health checks. Consequently, Kubernetes routed all live traffic away.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-12-mid",
    level: "Level 2: Mid-Level",
    title: "Unit 12: Past Continuous vs Past Simple",
    tag: "B1 - B2",
    subtitle: "Interrupci\u00f3n de procesos: 'While the migration was running, the network dropped'",
    ruleSummary: "Usa Past Continuous ('was running', 'were deploying') para la tarea de fondo que estaba en curso. Usa Past Simple ('dropped', 'failed') para el evento puntual que interrumpi\u00f3 la acci\u00f3n.",
    comparisonExamples: [
      {
        'wrong': "While I deployed, the alert was firing.",
        'right': "While I was deploying, the alert fired.",
        'tip': "El proceso en progreso lleva Past Continuous y la interrupci\u00f3n Past Simple.",
      },
      {
        'wrong': "The database crashed when we were run the benchmark.",
        'right': "The database crashed while we were running the benchmark.",
        'tip': "Usa 'while' con la forma continua del verbo.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 208,
        level: "Level 2: Mid-Level",
        unitTitle: "Unit 12: Past Continuous vs Past Simple",
        prompt: "While our background job _____ the transaction table, a sudden dead-lock occurred.",
        contextSentence: "Process interruption narrative.",
        options: ["was backfilling", "backfilled", "is backfilling", "has backfilled"],
        correctAnswer: "was backfilling",
        spanishExplanation: "La acci\u00f3n continua de fondo interrumpida por el deadlock requiere Past Continuous ('was backfilling').",
        audioText: "While our background job was backfilling the transaction table, a sudden dead-lock occurred.",
      ),
      GrammarQuestion(
        id: 209,
        level: "Level 2: Mid-Level",
        unitTitle: "Unit 12: Past Continuous vs Past Simple",
        prompt: "The automated canary script aborted immediately when latency metrics _____ the 200ms threshold.",
        contextSentence: "Punctual threshold breach.",
        options: ["exceeded", "were exceeding", "have exceeded", "had exceed"],
        correctAnswer: "exceeded",
        spanishExplanation: "El cruce puntual del umbral de latencia se formula en Past Simple ('exceeded').",
        audioText: "The automated canary script aborted immediately when latency metrics exceeded the 200ms threshold.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-13-mid",
    level: "Level 2: Mid-Level",
    title: "Unit 13: Third Conditional in Post-Mortems",
    tag: "B1 - B2",
    subtitle: "An\u00e1lisis contraf\u00e1ctico: 'If we had cached the query, the DB wouldn't have crashed'",
    ruleSummary: "El Tercer Condicional formula escenarios hipot\u00e9ticos pasados que no sucedieron. Estructura: If + Past Perfect (had + V3), would have + V3 ('If we had set up alerts, we would have caught the regression earlier').",
    comparisonExamples: [
      {
        'wrong': "If we had cache the endpoint, the server would not crash.",
        'right': "If we had cached the endpoint, the server would not have crashed.",
        'tip': "Ambas cl\u00e1usulas deben reflejar el pasado irreal (had + V3 ... would have + V3).",
      },
      {
        'wrong': "If we would have tested in staging, we avoided the bug.",
        'right': "If we had tested in staging, we would have avoided the bug.",
        'tip': "NUNCA pongas 'would have' en la cl\u00e1usula con 'If'.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 210,
        level: "Level 2: Mid-Level",
        unitTitle: "Unit 13: Third Conditional in Post-Mortems",
        prompt: "If we _____ strict rate limiting on the auth route, the DDoS attack would not have overwhelmed our gateway.",
        contextSentence: "Security post-mortem counterfactual.",
        options: ["had enforced", "would enforce", "enforced", "would have enforced"],
        correctAnswer: "had enforced",
        spanishExplanation: "En la condici\u00f3n del tercer condicional se usa Past Perfect ('had enforced').",
        audioText: "If we had enforced strict rate limiting on the auth route, the DDoS attack would not have overwhelmed our gateway.",
      ),
      GrammarQuestion(
        id: 211,
        level: "Level 2: Mid-Level",
        unitTitle: "Unit 13: Third Conditional in Post-Mortems",
        prompt: "Had we enabled read replicas sooner, the primary database _____ during peak Black Friday traffic.",
        contextSentence: "Inverted third conditional.",
        options: ["would not have stalled", "did not stall", "will not stall", "would not stall"],
        correctAnswer: "would not have stalled",
        spanishExplanation: "La consecuencia pasada no cumplida requiere 'would not have stalled'.",
        audioText: "Had we enabled read replicas sooner, the primary database would not have stalled during peak Black Friday traffic.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-14-mid",
    level: "Level 2: Mid-Level",
    title: "Unit 14: Relative Clauses for Tech Definitions",
    tag: "B1 - B2",
    subtitle: "Definir componentes con 'which', 'that', 'where' sin ambig\u00fcedad",
    ruleSummary: "Usa 'which' con comas para informaci\u00f3n adicional no restrictiva ('Redis, which is an in-memory datastore, provides sub-millisecond lookups'). Usa 'that' sin comas para identificar restrictivamente ('A broker that supports partitioning').",
    comparisonExamples: [
      {
        'wrong': "Postgres that is an open-source database supports JSON.",
        'right': "Postgres, which is an open-source database, supports JSON.",
        'tip': "Informaci\u00f3n complementaria no esencial sobre un nombre propio va entre comas con 'which'.",
      },
      {
        'wrong': "The microservice which handles billing crashed.",
        'right': "The microservice that handles billing crashed.",
        'tip': "Para especificar de qu\u00e9 microservicio exacto hablas, usa cl\u00e1usula restrictiva con 'that'.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 212,
        level: "Level 2: Mid-Level",
        unitTitle: "Unit 14: Relative Clauses for Tech Definitions",
        prompt: "We implemented a circuit breaker pattern _____ isolates failing third-party payment gateways.",
        contextSentence: "Essential defining clause.",
        options: ["that", "where", "whom", "what"],
        correctAnswer: "that",
        spanishExplanation: "Cl\u00e1usula restrictiva esencial que define la funci\u00f3n del patr\u00f3n: se usa 'that'.",
        audioText: "We implemented a circuit breaker pattern that isolates failing third-party payment gateways.",
      ),
      GrammarQuestion(
        id: 213,
        level: "Level 2: Mid-Level",
        unitTitle: "Unit 14: Relative Clauses for Tech Definitions",
        prompt: "Kafka, _____ acts as our central event backbone, decouples ingestion from analytical processing.",
        contextSentence: "Non-restrictive clause between commas.",
        options: ["which", "that", "what", "where"],
        correctAnswer: "which",
        spanishExplanation: "Entre comas para informaci\u00f3n explicativa adicional sobre un sujeto conocido se usa 'which'.",
        audioText: "Kafka, which acts as our central event backbone, decouples ingestion from analytical processing.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-15-mid",
    level: "Level 2: Mid-Level",
    title: "Unit 15: Gerunds vs Infinitives in Dev Workflows",
    tag: "B1 - B2",
    subtitle: "Avoiding, Recommending, Stopping: verbos seguidos de -ing o to + infinitivo",
    ruleSummary: "Verbos de arquitectura y c\u00f3digo como 'avoid', 'consider', 'finish', 'recommend' rigen gerundio ('avoid blocking the thread', 'recommend sharding the DB'). Verbos como 'decide', 'refuse', 'attempt' rigen infinitivo ('decided to migrate').",
    comparisonExamples: [
      {
        'wrong': "We should avoid to block the UI isolate.",
        'right': "We should avoid blocking the UI isolate.",
        'tip': "'Avoid' va siempre seguido de gerundio (-ing).",
      },
      {
        'wrong': "The team decided adopting GraphQL.",
        'right': "The team decided to adopt GraphQL.",
        'tip': "'Decide' va seguido de infinitivo con 'to'.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 214,
        level: "Level 2: Mid-Level",
        unitTitle: "Unit 15: Gerunds vs Infinitives in Dev Workflows",
        prompt: "To prevent cold-start latency, we strongly recommend _____ container instances pre-warmed.",
        contextSentence: "Architectural recommendation.",
        options: ["keeping", "to keep", "keep", "kept"],
        correctAnswer: "keeping",
        spanishExplanation: "'Recommend' rige gerundio ('keeping') cuando se refiere a la acci\u00f3n recomendada.",
        audioText: "To prevent cold-start latency, we strongly recommend keeping container instances pre-warmed.",
      ),
      GrammarQuestion(
        id: 215,
        level: "Level 2: Mid-Level",
        unitTitle: "Unit 15: Gerunds vs Infinitives in Dev Workflows",
        prompt: "The architecture committee decided _____ the monolithic database into domain services.",
        contextSentence: "Technical decision.",
        options: ["to partition", "partitioning", "partition", "for partitioning"],
        correctAnswer: "to partition",
        spanishExplanation: "'Decide' requiere infinitivo con 'to' ('to partition').",
        audioText: "The architecture committee decided to partition the monolithic database into domain services.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-16-mid",
    level: "Level 2: Mid-Level",
    title: "Unit 16: Passive Voice with Agents in Reviews",
    tag: "B1 - B2",
    subtitle: "'Designed by the infrastructure team': atribuci\u00f3n formal de responsabilidades",
    ruleSummary: "En code reviews y especificaciones de arquitectura, la combinaci\u00f3n de voz pasiva con complemento agente ('by + entity') confiere una autoridad t\u00e9cnica formal y neutral: 'The caching policy was established by the security guild'.",
    comparisonExamples: [
      {
        'wrong': "The pipeline was created from the DevOps team.",
        'right': "The pipeline was created by the DevOps team.",
        'tip': "El agente que realiza la acci\u00f3n en voz pasiva se introduce con 'by', no 'from'.",
      },
      {
        'wrong': "The PR was approved through the tech lead.",
        'right': "The PR was approved by the tech lead.",
        'tip': "El sujeto agente de la pasiva rige 'by'.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 216,
        level: "Level 2: Mid-Level",
        unitTitle: "Unit 16: Passive Voice with Agents in Reviews",
        prompt: "The revised microservice contract was thoroughly reviewed and validated _____ our security architects.",
        contextSentence: "Design review compliance.",
        options: ["by", "from", "through", "with"],
        correctAnswer: "by",
        spanishExplanation: "El agente de la acci\u00f3n en voz pasiva se introduce siempre con 'by'.",
        audioText: "The revised microservice contract was thoroughly reviewed and validated by our security architects.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-17-senior",
    level: "Level 3: Senior",
    title: "Unit 3: Active Voice & Leadership Impact",
    tag: "B2 - C1",
    subtitle: "C\u00f3mo proponer cambios y defender trade-offs con diplomacia t\u00e9cnica",
    ruleSummary: "Los arquitectos senior nunca afirman verdades absolutas ('Microservices are always better'). Usan 'hedging' para matizar el contexto: 'It might be prudent to consider...', 'Tend to experience...', 'Arguably the most resilient approach'.",
    comparisonExamples: [
      {
        'wrong': "GraphQL is obviously superior to REST in every way.",
        'right': "In read-heavy mobile clients, GraphQL tends to offer superior bandwidth efficiency.",
        'tip': "Usa 'tends to' y acota el \u00e1mbito t\u00e9cnico para ganar credibilidad como senior.",
      },
      {
        'wrong': "We must rewrite everything in Rust immediately.",
        'right': "It might be worthwhile exploring Rust for our CPU-bound worker threads.",
        'tip': "'It might be worthwhile' suena reflexivo y maduro.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 301,
        level: "Level 3: Senior",
        unitTitle: "Unit 3: Active Voice & Leadership Impact",
        prompt: "Given our read-heavy traffic pattern, it _____ to introduce a write-through caching layer.",
        contextSentence: "Diplomatic architecture recommendation in RFC.",
        options: ["might be prudent", "is strictly required without debate", "has to make it", "will surely enforce"],
        correctAnswer: "might be prudent",
        spanishExplanation: "'It might be prudent' es el est\u00e1ndar de oro en arquitectura senior para sugerir soluciones sin sonar dogm\u00e1tico.",
        audioText: "Given our read-heavy traffic pattern, it might be prudent to introduce a write-through caching layer.",
      ),
      GrammarQuestion(
        id: 302,
        level: "Level 3: Senior",
        unitTitle: "Unit 3: Active Voice & Leadership Impact",
        prompt: "Monolithic architectures _____ suffer from tight coupling as the headcount scales past fifty engineers.",
        contextSentence: "Nuanced general observation.",
        options: ["tend to", "will forever", "must inevitably", "are bound without exception to"],
        correctAnswer: "tend to",
        spanishExplanation: "'Tend to' expresa una tendencia emp\u00edrica sin caer en afirmaciones absolutistas.",
        audioText: "Monolithic architectures tend to suffer from tight coupling as the headcount scales past fifty engineers.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-18-senior",
    level: "Level 3: Senior",
    title: "Unit 18: Inversion for Dramatic Retrospectives",
    tag: "B2 - C1",
    subtitle: "Estructuras invertidas: 'Never have we observed such high throughput'",
    ruleSummary: "En presentaciones t\u00e9cnicas de alto impacto y defensas de arquitectura, las estructuras invertidas con adverbios negativos ('Never have we...', 'Rarely do systems...', 'Not only did we scale...') transmiten un dominio verbal nativo y contundente.",
    comparisonExamples: [
      {
        'wrong': "We never have seen such a dramatic latency decrease.",
        'right': "Never have we observed such a dramatic reduction in tail latency.",
        'tip': "La inversi\u00f3n adverbial ('Never + auxiliary + subject + verb') genera impacto ret\u00f3rico.",
      },
      {
        'wrong': "Not only we reduced cloud costs, but also improved uptime.",
        'right': "Not only did we reduce cloud costs, but we also improved overall system availability.",
        'tip': "'Not only' inicial requiere inversi\u00f3n con auxiliar ('did we reduce').",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 303,
        level: "Level 3: Senior",
        unitTitle: "Unit 18: Inversion for Dramatic Retrospectives",
        prompt: "_____ such catastrophic cascading failures until the upstream gateway dropped connection throttling.",
        contextSentence: "High-impact retrospective statement.",
        options: ["Rarely had we witnessed", "We had rarely witnessed not", "Rarely we witnessed", "Rarely did we witnessed"],
        correctAnswer: "Rarely had we witnessed",
        spanishExplanation: "La inversi\u00f3n adverbial formal exige 'Rarely had we witnessed' (adverbio + auxiliar + sujeto + participio).",
        audioText: "Rarely had we witnessed such catastrophic cascading failures until the upstream gateway dropped connection throttling.",
      ),
      GrammarQuestion(
        id: 304,
        level: "Level 3: Senior",
        unitTitle: "Unit 18: Inversion for Dramatic Retrospectives",
        prompt: "Not only _____ the P99 response time to under 15 milliseconds, but we also cut infrastructure spend by 28%.",
        contextSentence: "Executive architectural achievement summary.",
        options: ["did we reduce", "we reduced", "reduced we", "have we reduce"],
        correctAnswer: "did we reduce",
        spanishExplanation: "'Not only' al inicio de oraci\u00f3n requiere inversi\u00f3n auxiliar en pasado: 'did we reduce'.",
        audioText: "Not only did we reduce the P99 response time to under 15 milliseconds, but we also cut infrastructure spend by 28%.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-19-senior",
    level: "Level 3: Senior",
    title: "Unit 19: Expressing Complex Trade-Offs",
    tag: "B2 - C1",
    subtitle: "Whereas, While, On the other hand, In contrast en decisiones de dise\u00f1o",
    ruleSummary: "Todo dise\u00f1o de sistemas implica compromisos. Usa 'Whereas' o 'While' para contrastar dos enfoques en una sola oraci\u00f3n balanceada ('While NoSQL provides horizontal elasticity, ACID compliance is sacrificed').",
    comparisonExamples: [
      {
        'wrong': "Postgres has strong consistency, on the other hand Cassandra scales better.",
        'right': "While PostgreSQL offers robust ACID guarantees, Cassandra scales more gracefully under massive write throughput.",
        'tip': "'While' crea una cl\u00e1usula subordinada elegante que pondera pros y contras.",
      },
      {
        'wrong': "Microservices are fast but they are hard.",
        'right': "Whereas microservices foster team autonomy, they introduce substantial operational complexity.",
        'tip': "Usa 'Whereas' para contrastar dimensiones de arquitectura formalmente.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 305,
        level: "Level 3: Senior",
        unitTitle: "Unit 19: Expressing Complex Trade-Offs",
        prompt: "_____ event-driven messaging decouples downstream consumers, it introduces eventual consistency overhead.",
        contextSentence: "Balanced architectural trade-off formulation.",
        options: ["While", "Despite", "Because", "However"],
        correctAnswer: "While",
        spanishExplanation: "'While' (= mientras que) encabeza la concesi\u00f3n t\u00e9cnica contrapuesta a la consecuencia principal.",
        audioText: "While event-driven messaging decouples downstream consumers, it introduces eventual consistency overhead.",
      ),
      GrammarQuestion(
        id: 306,
        level: "Level 3: Senior",
        unitTitle: "Unit 19: Expressing Complex Trade-Offs",
        prompt: "Synchronous RPC guarantees immediate response feedback; _____, asynchronous pub/sub maximizes ingestion throughput.",
        contextSentence: "Semi-colon transition contrasting systems.",
        options: ["in contrast", "although", "whereas", "owing to"],
        correctAnswer: "in contrast",
        spanishExplanation: "Tras punto y coma y seguido de coma, la locuci\u00f3n adverbial de transici\u00f3n adecuada es 'in contrast,'.",
        audioText: "Synchronous RPC guarantees immediate response feedback; in contrast, asynchronous pub/sub maximizes ingestion throughput.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-20-senior",
    level: "Level 3: Senior",
    title: "Unit 20: Subjunctive in Formal RFC Proposals",
    tag: "B2 - C1",
    subtitle: "Estructuras de mandato t\u00e9cnico: 'I propose that the API be versioned'",
    ruleSummary: "En RFCs y recomendaciones de comit\u00e9s t\u00e9cnicos formales en ingl\u00e9s, los verbos de recomendaci\u00f3n ('recommend', 'mandate', 'insist', 'propose') toman subjuntivo (verbo en forma base sin conjugaci\u00f3n): 'We propose that every service expose a health metric'.",
    comparisonExamples: [
      {
        'wrong': "I recommend that the database is upgraded tonight.",
        'right': "I recommend that the database be upgraded tonight.",
        'tip': "El subjuntivo formal en ingl\u00e9s t\u00e9cnico utiliza la forma base 'be', no 'is'.",
      },
      {
        'wrong': "The lead insisted that he writes unit tests.",
        'right': "The lead insisted that he write comprehensive integration tests.",
        'tip': "El subjuntivo de tercera persona singular usa 'write', no 'writes'.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 307,
        level: "Level 3: Senior",
        unitTitle: "Unit 20: Subjunctive in Formal RFC Proposals",
        prompt: "The architecture governance board mandates that each newly created microservice _____ an OpenAPI contract.",
        contextSentence: "Formal company engineering policy.",
        options: ["publish", "publishes", "is publishing", "published"],
        correctAnswer: "publish",
        spanishExplanation: "La cl\u00e1usula subjuntiva tras 'mandates that' exige la forma base pura del verbo ('publish').",
        audioText: "The architecture governance board mandates that each newly created microservice publish an OpenAPI contract.",
      ),
      GrammarQuestion(
        id: 308,
        level: "Level 3: Senior",
        unitTitle: "Unit 20: Subjunctive in Formal RFC Proposals",
        prompt: "We strongly recommend that the legacy authentication cluster _____ decommissioned by Q4.",
        contextSentence: "Technical roadmap proposal.",
        options: ["be", "is", "was", "will be"],
        correctAnswer: "be",
        spanishExplanation: "El subjuntivo pasivo con 'recommend that' utiliza 'be decommissioned'.",
        audioText: "We strongly recommend that the legacy authentication cluster be decommissioned by Q4.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-21-senior",
    level: "Level 3: Senior",
    title: "Unit 21: Mixed Conditionals in Tech Debt",
    tag: "B2 - C1",
    subtitle: "Pasado que impacta el presente: 'If we had refactored, we would be scalable now'",
    ruleSummary: "Los condicionales mixtos combinan una causa en el pasado (had + V3) con un estado resultante en el presente (would + verbo base): 'If we had containerized our workloads back then, we would not struggle with server drift today'.",
    comparisonExamples: [
      {
        'wrong': "If we migrated last year, we would be fine today.",
        'right': "If we had migrated last year, we would be far more competitive today.",
        'tip': "La acci\u00f3n pasada es irrepetible ('had migrated'); el efecto actual es presente ('would be').",
      },
      {
        'wrong': "If we had cached early, we would have been faster today.",
        'right': "If we had cached early, we would have lower latency today.",
        'tip': "'Today' rige 'would have lower latency', no 'would have had'.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 309,
        level: "Level 3: Senior",
        unitTitle: "Unit 21: Mixed Conditionals in Tech Debt",
        prompt: "If the previous team _____ an automated migration harness, we would not be spending half our sprint resolving manual schema drifts today.",
        contextSentence: "Technical debt evaluation.",
        options: ["had established", "established", "would establish", "has established"],
        correctAnswer: "had established",
        spanishExplanation: "Condici\u00f3n mixta: acci\u00f3n no realizada en el pasado con impacto en el presente ('had established').",
        audioText: "If the previous team had established an automated migration harness, we would not be spending half our sprint resolving manual schema drifts today.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-22-senior",
    level: "Level 3: Senior Architect",
    title: "Unit 22: Cleft Sentences for Emphasis",
    tag: "B2 - C1",
    subtitle: "Estructuras de realce: 'What we achieved was a 40% latency reduction'",
    ruleSummary: "Las 'cleft sentences' dividen la informaci\u00f3n para enfocar el m\u00e9rito principal de tu equipo ante el entrevistador: 'What really transformed our delivery velocity was continuous deployment' o 'It was our database partitioning that prevented the downtime'.",
    comparisonExamples: [
      {
        'wrong': "We improved the caching and that made the difference.",
        'right': "What made the critical difference was our multi-tiered caching strategy.",
        'tip': "La estructura 'What [acci\u00f3n] was [logro]' suena profesional y segura.",
      },
      {
        'wrong': "The asynchronous queue saved the system.",
        'right': "It was the asynchronous queue that buffered the traffic spike and prevented data loss.",
        'tip': "La cleft con 'It was X that Y' enfatiza el factor clave.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 310,
        level: "Level 3: Senior Architect",
        unitTitle: "Unit 22: Cleft Sentences for Emphasis",
        prompt: "_____ enabled us to maintain five-nines availability was our automated multi-region failover strategy.",
        contextSentence: "STAR story focal emphasis.",
        options: ["What", "Which", "That", "It"],
        correctAnswer: "What",
        spanishExplanation: "Wh-cleft sentence introducida por 'What' para enfatizar el componente clave del \u00e9xito.",
        audioText: "What enabled us to maintain five-nines availability was our automated multi-region failover strategy.",
      ),
      GrammarQuestion(
        id: 311,
        level: "Level 3: Senior Architect",
        unitTitle: "Unit 22: Cleft Sentences for Emphasis",
        prompt: "It was our early investment in observability _____ allowed us to pinpoint the memory leak within minutes.",
        contextSentence: "Attribution cleft sentence.",
        options: ["that", "which", "what", "who"],
        correctAnswer: "that",
        spanishExplanation: "La estructura 'It was [X] that [Y]' rige 'that' como nexo enf\u00e1tico.",
        audioText: "It was our early investment in observability that allowed us to pinpoint the memory leak within minutes.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-23-senior",
    level: "Level 3: Senior Architect",
    title: "Unit 23: Participle Clauses for Concise Docs",
    tag: "B2 - C1",
    subtitle: "Sintaxis t\u00e9cnica compacta: 'Having decoupled the queue, we lowered CPU spikes'",
    ruleSummary: "Las cl\u00e1usulas de participio ('Having decoupled...', 'Utilizing an LSM-tree...') reemplazan oraciones largas de causa o tiempo y permiten un estilo de escritura y habla ejecutivo, conciso y de alta densidad.",
    comparisonExamples: [
      {
        'wrong': "Because we migrated the DB, we observed lower latency.",
        'right': "Having migrated the database to DynamoDB, we eliminated operational maintenance entirely.",
        'tip': "'Having + participio' indica que una tarea concluy\u00f3 exitosamente antes de la siguiente.",
      },
      {
        'wrong': "When we use Redis, we can cache responses.",
        'right': "Leveraging Redis as an edge cache, our proxy serves 90% of requests without touching the origin.",
        'tip': "El participio presente 'Leveraging...' confiere sofisticaci\u00f3n t\u00e9cnica.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 312,
        level: "Level 3: Senior Architect",
        unitTitle: "Unit 23: Participle Clauses for Concise Docs",
        prompt: "_____ the monolithic repository into domain packages, we reduced CI pipeline build times from forty minutes to six.",
        contextSentence: "Executive technical summary.",
        options: ["Having refactored", "After we refactor", "Refactoring have", "We had refactored"],
        correctAnswer: "Having refactored",
        spanishExplanation: "'Having refactored' resume de forma compacta y elegante una acci\u00f3n completada con \u00e9xito.",
        audioText: "Having refactored the monolithic repository into domain packages, we reduced CI pipeline build times from forty minutes to six.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-24-senior",
    level: "Level 3: Senior Architect",
    title: "Unit 24: Discourse Markers in System Design",
    tag: "B2 - C1",
    subtitle: "Transiciones fluidas durante entrevistas de System Design de 45 minutos",
    ruleSummary: "Guiar al entrevistador requiere marcadores de transici\u00f3n deliberados: 'Moving on to data persistence...', 'With regard to horizontal scalability...', 'Turning our attention to fault tolerance...'. Demuestran estructura mental y liderazgo.",
    comparisonExamples: [
      {
        'wrong': "Now I talk about the database.",
        'right': "Moving on to our data persistence layer, let's analyze read-write ratios.",
        'tip': "'Moving on to...' es la transici\u00f3n profesional perfecta durante un whiteboard design.",
      },
      {
        'wrong': "About the security, we use OAuth.",
        'right': "With respect to access governance, OAuth 2.0 with short-lived tokens is our baseline.",
        'tip': "'With respect to...' introduce dominios de dise\u00f1o formalmente.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 313,
        level: "Level 3: Senior Architect",
        unitTitle: "Unit 24: Discourse Markers in System Design",
        prompt: "Now that we have scoped the ingestion API, _____ to the storage tier and discuss data partitioning strategies.",
        contextSentence: "System design interview transition.",
        options: ["let us transition", "we go now", "I make a jump", "talking next"],
        correctAnswer: "let us transition",
        spanishExplanation: "'Let us transition to...' marca un cambio de secci\u00f3n ordenado y colaborativo con el entrevistador.",
        audioText: "Now that we have scoped the ingestion API, let us transition to the storage tier and discuss data partitioning strategies.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-25-staff",
    level: "Level 4: Staff / Lead",
    title: "Unit 4: Strategic Negotiation & Idioms",
    tag: "C1",
    subtitle: "C\u00f3mo hablarle a VPs y directores con convicci\u00f3n fundamentada en datos",
    ruleSummary: "A nivel Staff/Principal, el lenguaje debe ser asertivo y cuantitativo: 'The data unequivocally demonstrates that...', 'I strongly advocate allocating 20% of sprint capacity to technical debt reduction'.",
    comparisonExamples: [
      {
        'wrong': "Maybe we should think about refactoring if you agree.",
        'right': "I strongly recommend investing in our event backbone this quarter to mitigate catastrophic Q4 outage risk.",
        'tip': "Sustituye la timidez por recomendaciones asertivas respaldadas por impacto de negocio.",
      },
      {
        'wrong': "The latency is somewhat bad.",
        'right': "The tail latency poses a direct threat to our checkout conversion funnels.",
        'tip': "Conecta problemas t\u00e9cnicos directamente con m\u00e9tricas de negocio.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 401,
        level: "Level 4: Staff / Lead",
        unitTitle: "Unit 4: Strategic Negotiation & Idioms",
        prompt: "To convince senior leadership to invest in distributed tracing, a staff engineer asserts:",
        contextSentence: "Executive persuasion in engineering committee.",
        options: ["The telemetry data unequivocally demonstrates that mean-time-to-resolution dropped by 65% in pilot squads.", "Maybe we can try some tracing tools if anyone likes it.", "I think tracing is very pretty and modern.", "We need tracing because Google uses it."],
        correctAnswer: "The telemetry data unequivocally demonstrates that mean-time-to-resolution dropped by 65% in pilot squads.",
        spanishExplanation: "A nivel Staff/Principal, las decisiones se defienden con datos concluyentes ('unequivocally demonstrates') y m\u00e9tricas de negocio ('MTTR').",
        audioText: "The telemetry data unequivocally demonstrates that mean-time-to-resolution dropped by 65% in pilot squads.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-26-staff",
    level: "Level 4: Staff / Lead",
    title: "Unit 26: Risk Mitigation & Concessive Clauses",
    tag: "C1",
    subtitle: "Notwithstanding, Albeit, In spite of en evaluaciones de riesgo corporativo",
    ruleSummary: "Las cl\u00e1usulas concesivas avanzadas permiten reconocer riesgos sin restar firmeza a la propuesta: 'Notwithstanding the initial capital expenditure, migrating to self-hosted Kubernetes yields a 40% margin improvement within 18 months'.",
    comparisonExamples: [
      {
        'wrong': "Although the high cost, we must migrate.",
        'right': "Notwithstanding the upfront migration overhead, the strategic elasticity justifies the investment.",
        'tip': "'Notwithstanding' rige frase sustantiva y denota alto registro ejecutivo.",
      },
      {
        'wrong': "It is slow but good.",
        'right': "Our consensus protocol provides robust correctness, albeit at the expense of marginal write latency.",
        'tip': "'Albeit' introduce concesiones sutiles de forma impecable.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 402,
        level: "Level 4: Staff / Lead",
        unitTitle: "Unit 26: Risk Mitigation & Concessive Clauses",
        prompt: "_____ the steep initial learning curve of Rust, the elimination of memory-safety vulnerabilities resulted in a net productivity gain.",
        contextSentence: "High-level technology trade-off defense.",
        options: ["Notwithstanding", "Although", "Despite of", "Even"],
        correctAnswer: "Notwithstanding",
        spanishExplanation: "'Notwithstanding' introduce una frase nominal concesiva con el m\u00e1ximo registro de formalidad.",
        audioText: "Notwithstanding the steep initial learning curve of Rust, the elimination of memory-safety vulnerabilities resulted in a net productivity gain.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-27-staff",
    level: "Level 4: Staff / Lead",
    title: "Unit 27: Counterfactual Reasoning in RFCs",
    tag: "C1",
    subtitle: "Estructuras sin 'If': 'Had we not implemented backpressure, failure would have ensued'",
    ruleSummary: "La inversi\u00f3n sin 'If' ('Had we not...', 'Were we to adopt...') es la marca definitiva de prosa t\u00e9cnica formal en RFCs de arquitectura cr\u00edtica y defensas ejecutivas ante CTOs.",
    comparisonExamples: [
      {
        'wrong': "If we would not have backpressure, the queue died.",
        'right': "Had we not implemented adaptive backpressure, cascading worker exhaustion would have ensued.",
        'tip': "'Had we not [V3] ... would have [V3]' es la forma m\u00e1s refinada del condicional pasado.",
      },
      {
        'wrong': "If we would decide to rewrite, it costs too much.",
        'right': "Were we to undertake a complete rewrite, the opportunity cost would stifle roadmap delivery for six months.",
        'tip': "'Were we to [infinitive]' formula hip\u00f3tesis futuras con elegancia.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 403,
        level: "Level 4: Staff / Lead",
        unitTitle: "Unit 27: Counterfactual Reasoning in RFCs",
        prompt: "_____ we to deprecate the v1 gateway without backward compatibility shims, our enterprise partner integrations would instantly fracture.",
        contextSentence: "Formal hypothetical risk evaluation.",
        options: ["Were", "If", "Had", "Should"],
        correctAnswer: "Were",
        spanishExplanation: "La inversi\u00f3n de segundo condicional hipot\u00e9tico para el futuro se construye con 'Were we to [verb]'.",
        audioText: "Were we to deprecate the v1 gateway without backward compatibility shims, our enterprise partner integrations would instantly fracture.",
      ),
      GrammarQuestion(
        id: 404,
        level: "Level 4: Staff / Lead",
        unitTitle: "Unit 27: Counterfactual Reasoning in RFCs",
        prompt: "Had our site reliability team not acted within ninety seconds, the cache stampede _____ down the payment cluster.",
        contextSentence: "Severe incident counterfactual.",
        options: ["would have brought", "will bring", "brought", "had brought"],
        correctAnswer: "would have brought",
        spanishExplanation: "La cl\u00e1usula principal de un tercer condicional invertido requiere 'would have brought'.",
        audioText: "Had our site reliability team not acted within ninety seconds, the cache stampede would have brought down the payment cluster.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-28-staff",
    level: "Level 4: Staff / Lead",
    title: "Unit 28: Advanced Modal Stances for Roadmaps",
    tag: "C1",
    subtitle: "Is bound to, Is poised to, Ought to en compromisos de entrega",
    ruleSummary: "En compromisos estrat\u00e9gicos, los modales compuestos ofrecen precisi\u00f3n sobre certeza y probabilidad: 'Our platform is poised to absorb a 10x traffic spike' (est\u00e1 lista/preparada), 'Unchecked tech debt is bound to cause regressions' (inevitablemente causar\u00e1).",
    comparisonExamples: [
      {
        'wrong': "The database will surely crash eventually.",
        'right': "Without automated indexing audits, the query engine is bound to degrade under scale.",
        'tip': "'Is bound to' denota un desenlace inevitable basado en leyes t\u00e9cnicas.",
      },
      {
        'wrong': "The new architecture is ready to scale.",
        'right': "Our refactored core is poised to support multi-region expansion seamlessly.",
        'tip': "'Is poised to' denota preparaci\u00f3n estrat\u00e9gica de primer nivel.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 405,
        level: "Level 4: Staff / Lead",
        unitTitle: "Unit 28: Advanced Modal Stances for Roadmaps",
        prompt: "Following the successful Kubernetes cluster consolidation, our platform _____ expand into the APAC region next quarter.",
        contextSentence: "Strategic roadmap readiness.",
        options: ["is poised to", "is bound without", "ought have to", "can to"],
        correctAnswer: "is poised to",
        spanishExplanation: "'Is poised to' significa estar en posici\u00f3n \u00f3ptima y listo para dar el siguiente paso estrat\u00e9gico.",
        audioText: "Following the successful Kubernetes cluster consolidation, our platform is poised to expand into the APAC region next quarter.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-29-staff",
    level: "Level 4: Staff / Lead",
    title: "Unit 29: Nominalization for Executive Summaries",
    tag: "C1",
    subtitle: "De verbos a sustantivos de alto nivel: 'Decoupling facilitated scalability'",
    ruleSummary: "La nominalizaci\u00f3n transforma oraciones coloquiales centradas en acciones ('Because we decoupled the services, they can scale') en declaraciones condensadas de impacto ('Service decoupling facilitated autonomous horizontal scalability').",
    comparisonExamples: [
      {
        'wrong': "We refactored how we store logs so developers find bugs faster.",
        'right': "Centralization of telemetry ingestion substantially accelerated defect discovery cycles.",
        'tip': "La nominalizaci\u00f3n produce res\u00famenes densos, claros y orientados a resultados.",
      },
      {
        'wrong': "When we migrated to cloud, we saved money.",
        'right': "Cloud infrastructure migration achieved a 32% reduction in recurring compute costs.",
        'tip': "Presenta los logros como hitos corporativos consolidados.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 406,
        level: "Level 4: Staff / Lead",
        unitTitle: "Unit 29: Nominalization for Executive Summaries",
        prompt: "Transform this conversational sentence: 'Because we automated the regression suite, we released faster.'",
        contextSentence: "Staff-level communication refinement.",
        options: ["Test harness automation substantially accelerated our release cadence.", "We did automation so we can run very fast now.", "Automating stuff made everybody happy and quick.", "Because tests were automatic, things went rapid."],
        correctAnswer: "Test harness automation substantially accelerated our release cadence.",
        spanishExplanation: "La nominalizaci\u00f3n concisa ('Test harness automation substantially accelerated our release cadence') es el sello distintivo del liderazgo t\u00e9cnico.",
        audioText: "Test harness automation substantially accelerated our release cadence.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-30-staff",
    level: "Level 4: Staff / Lead",
    title: "Unit 30: Tactful Disagreement & Steering",
    tag: "C1",
    subtitle: "Disentir de forma constructiva con otros Staff Engineers y Directores",
    ruleSummary: "El desacuerdo constructivo preserva la relaci\u00f3n profesional a la vez que defiende la integridad del sistema: 'I see your rationale regarding speed to market; however, from an operational resilience standpoint, skipping schema migrations introduces unacceptable liabilities'.",
    comparisonExamples: [
      {
        'wrong': "Your idea is bad and will crash the database.",
        'right': "I appreciate the ingenuity of this proposal; however, we must weigh it against our strict zero-data-loss SLA.",
        'tip': "Valida la intenci\u00f3n del interlocutor antes de presentar la objeci\u00f3n t\u00e9cnica objetiva.",
      },
      {
        'wrong': "I disagree with you completely.",
        'right': "While I recognize the short-term gains, my primary reservation centers on long-term maintainability.",
        'tip': "'My primary reservation centers on...' enfoca la discusi\u00f3n en el criterio, no en el ego.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 407,
        level: "Level 4: Staff / Lead",
        unitTitle: "Unit 30: Tactful Disagreement & Steering",
        prompt: "When tactfully dissenting with a Product Manager who wants to bypass database migrations to hit a marketing deadline, say:",
        contextSentence: "Cross-functional executive alignment.",
        options: ["While I understand the commercial urgency, bypassing migration validations exposes our billing engine to catastrophic data corruption risk.", "No, marketing people never understand how databases actually work.", "You will destroy the database if you do that.", "I disagree because code quality is always number one regardless of business."],
        correctAnswer: "While I understand the commercial urgency, bypassing migration validations exposes our billing engine to catastrophic data corruption risk.",
        spanishExplanation: "Equilibra la comprensi\u00f3n del objetivo de negocio ('commercial urgency') con una advertencia t\u00e9cnica objetiva y ponderada.",
        audioText: "While I understand the commercial urgency, bypassing migration validations exposes our billing engine to catastrophic data corruption risk.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-31-staff",
    level: "Level 4: Staff / Lead",
    title: "Unit 31: Strategic Vision & Architectural Roadmaps",
    tag: "C1",
    subtitle: "Formulaci\u00f3n de planes a 3 a\u00f1os y evoluci\u00f3n de plataformas tecnol\u00f3gicas",
    ruleSummary: "Los Staff y Principals deben proyectar la visi\u00f3n tecnol\u00f3gica hacia el futuro: 'Our three-year objective is to evolve our backend into an event-driven mesh that unlocks autonomous squad iteration without centralized coordination'.",
    comparisonExamples: [
      {
        'wrong': "We want to make the backend good in three years.",
        'right': "Our strategic ambition centers on modularizing domain boundaries to foster self-service platform engineering.",
        'tip': "Emplea vocabulario estrat\u00e9gico de ingenier\u00eda de plataformas.",
      },
      {
        'wrong': "We will buy more servers when we grow.",
        'right': "We are architecting our multi-cloud deployment strategy to ensure operational resilience against regional outages.",
        'tip': "Proyecta gobernanza y resiliencia a largo plazo.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 408,
        level: "Level 4: Staff / Lead",
        unitTitle: "Unit 31: Strategic Vision & Architectural Roadmaps",
        prompt: "How does a Lead Architect describe their long-term technical vision in an interview?",
        contextSentence: "Executive vision interview response.",
        options: ["Our multi-year strategy focuses on decoupling our transactional core to empower product teams with self-service event streams.", "I want our company to use the newest libraries always.", "We plan to rewrite everything every two years to stay fresh.", "My vision is having zero bugs in the entire company."],
        correctAnswer: "Our multi-year strategy focuses on decoupling our transactional core to empower product teams with self-service event streams.",
        spanishExplanation: "Combina arquitectura desacoplada con valor empresarial para los equipos de producto.",
        audioText: "Our multi-year strategy focuses on decoupling our transactional core to empower product teams with self-service event streams.",
      ),
    ],
  ),
  const GrammarUnit(
    id: "unit-32-staff",
    level: "Level 4: Staff / Lead",
    title: "Unit 32: Idiomatic Tech Leadership Expressions",
    tag: "C1",
    subtitle: "Bite the bullet, Move the needle, Touch base, Double-edged sword",
    ruleSummary: "Los modismos de liderazgo son comunes en empresas anglosajonas y entrevistas de FAANG/Silicon Valley: 'bite the bullet' (tomar una decisi\u00f3n dura necesaria), 'move the needle' (generar un impacto medible), 'touch base' (sincronizar brevemente), 'a double-edged sword' (arma de doble filo / trade-off).",
    comparisonExamples: [
      {
        'wrong': "We had to take the hard decision and kill the monolith.",
        'right': "We had to bite the bullet and deprecate the legacy monolithic backend.",
        'tip': "'Bite the bullet' es el modismo nativo est\u00e1ndar para decisiones inevitables y dif\u00edciles.",
      },
      {
        'wrong': "This refactor made good results in the metrics.",
        'right': "Our latency optimizations truly moved the needle on customer checkout conversion.",
        'tip': "'Moved the needle' denota impacto comercial tangible.",
      },
    ],
    questions: [
      GrammarQuestion(
        id: 409,
        level: "Level 4: Staff / Lead",
        unitTitle: "Unit 32: Idiomatic Tech Leadership Expressions",
        prompt: "When you must finally face an uncomfortable decision (e.g. deprecating a legacy system), you:",
        contextSentence: "Idiomatic expressions in engineering leadership.",
        options: ["Bite the bullet", "Break the ice", "Burn the midnight oil", "Spill the beans"],
        correctAnswer: "Bite the bullet",
        spanishExplanation: "'Bite the bullet' significa tomar una decisi\u00f3n dif\u00edcil o inc\u00f3moda que se ha estado postergando.",
        audioText: "We had to bite the bullet and deprecate the v1 monolithic API.",
      ),
      GrammarQuestion(
        id: 410,
        level: "Level 4: Staff / Lead",
        unitTitle: "Unit 32: Idiomatic Tech Leadership Expressions",
        prompt: "Explain that microservices have both distinct advantages and operational drawbacks:",
        contextSentence: "Balanced architectural nuance.",
        options: ["Adopting microservices is a double-edged sword: it unlocks scale but multiplies operational overhead.", "Microservices is a two-knife situation.", "It has two faces of a coin always.", "Microservices are both good and bad things."],
        correctAnswer: "Adopting microservices is a double-edged sword: it unlocks scale but multiplies operational overhead.",
        spanishExplanation: "'A double-edged sword' (un arma de doble filo) es el modismo t\u00e9cnico ideal para ponderar trade-offs.",
        audioText: "Adopting microservices is a double-edged sword: it unlocks scale but multiplies operational overhead.",
      ),
    ],
  ),
];
